### ISSUE TITLE
PROJECT_ROOT_FOR_DYNACONF doesn't work

### ISSUE THREAD

**Issue by kamac** [rochacbruno/dynaconf#106]
I've noticed there are two configuration variables:

PROJECT_ROOT_FOR_DYNACONF
SETTINGS_MODULE_FOR_DYNACONF

With following folder structure:
```
- project
- - settings.toml
- - start.py
```

If one does:
```
cd /
export PROJECT_ROOT_FOR_DYNACONF=/project
python project/start.py
```

It won't work. However, this does:
```
cd /
export SETTINGS_MODULE_FOR_DYNACONF=/project/settings.toml
python project/start.py
```

Any idea why that might be?

**Comment by rochacbruno** [comment]
@kamac problem fixed, will be in the next release next week
