### ISSUE TITLE
[RFC] Allow dynaconf cli to use a customized settings object

### ISSUE THREAD

**Issue by sirex** [rochacbruno/dynaconf#108]
I have a customized settings object:

```python
from dynaconf import LazySettings

settings = LazySettings(
    GLOBAL_ENV_FOR_DYNACONF='MYPROJECT',
    MERGE_ENABLED_FOR_DYNACONF=True,
)
```

When I run `dynaconf` cli tool, it knows nothing about my customization. How can I tell `dynaconf` cli tool to use my customized version of settings?

**Comment by rochacbruno** [comment]
Hi @sirex 
The dynaconf CLI is based on the environment variables only, in your case
```bash
GLOBAL_ENV_FOR_DYNACONF='MYPROJECT' MERGE_ENABLED_FOR_DYNACONF=True dynaconf list
```

Currently, there is no way to point to a customized object, but we can think about adding this functionality

**Ideas**:
1.
```bash
export INSTANCE_FOR_DYNACONF=myproject/folder/module.py   # dynaconf will look to a `LazySettings` inside it
```

2.
```bash
export INSTANCE_FOR_DYNACONF=myproject.module.other:settings 
```

3.
```bash
dynaconf list --instance=myproject.module.other.settings
```

I'll keep this issue as a tracker for this implementation

**Comment by sirex** [comment]
I like 2nd and 3rd options. And I can probably implement it myself. What RFC stands for? Ready for comments or Ready for commit?

**Comment by rochacbruno** [comment]
@sirex it is **R**equest **F**or **C**omments.
It will be nice if you can implement and send the PR.

I guess importlib allows to easily import based on a provided string.

```python
import importlib
instance_arg = "foo.bar:settings"  # read from command line or environment variable

try:
    mod_name, settings_object_name = instance_arg.rsplit(':')
except ValueError:  # no ":" separator found
    mod_name = instance_arg
    settings_object_name = "settings"  # assume the `settings` name if not provided

mod = importlib.import_module(mod_name)
return getattr(mod, settings_object_name)

```

**Comment by sirex** [comment]
https://github.com/rochacbruno/dynaconf/pull/109
