### ISSUE TITLE
settings.get: 'cast' and 'default' don't seem to work together

### ISSUE THREAD

**Issue by lroellin** [rochacbruno/dynaconf#119]
dynaconf 1.2.0 on Python 3.6.5

I have a setting that has a `default` and a `cast`: 
```settings.get("x.y", default=DEFAULT_X_Y, cast="@str")```

Now, `x.y` is not defined, but `DEFAULT_X_Y` is.

When using the debugger, I get (`>` are debugger inputs)
```
> settings.get("x.y")
None
> settings.get("x.y", default=DEFAULT_X_Y)
(value of DEFAULT_X_Y)
> settings.get("x.y", default=DEFAULT_X_Y, cast="@str")
{TypeError}'NoneType' object is not callable
```

I would have expected for `DEFAULT_X_Y` to be casted to str

**Comment by rochacbruno** [comment]
There is no `@str` converter https://github.com/rochacbruno/dynaconf/blob/master/dynaconf/utils/parse_conf.py#L16-L29

**Comment by rochacbruno** [comment]
There is no `@str` because env vars are strings by default and that feature is meant to use with env vars.

I recommend you to do

```py
settings.get("x.y", default=str(DEFAULT_X_Y))
```

to get the same results
