### ISSUE TITLE
How to use custom loader with flask

### ISSUE THREAD

**Issue by fantapop** [rochacbruno/dynaconf#122]
I'm trying to follow the instructions for using a custom loader with the flask extension.   I've tried a lot of different things but I can't get it working.

What I wanted to do was to use a custom loader to load json with commentjson instead of the default json (https://commentjson.readthedocs.io/en/latest/)

At first I was stumbling over the fact that the default loaders are checked before any external loaders. Hence, it was using the built in json loader to load my json file with comments in it and blowing up.  I then attempted to create a custom extension .cjson for my settings file but it still doesn't seem to work.  I can see my module load function getting called with the external loaders but it seems like the list of loaders is staticly defined here:

```
    // XXX if I add my file to SETTINGS_MODULE_FOR_DYNACONF it shows up in module_names
    for mod_file in (modules_names + found_files):
        # can be set to multiple files settings.py,settings.yaml,...

        # Cascade all loaders
        loaders = [
            {'ext': ct.YAML_EXTENSIONS, 'name': 'YAML', 'loader': yaml_loader},
            {'ext': ct.TOML_EXTENSIONS, 'name': 'TOML', 'loader': toml_loader},
            {'ext': ct.INI_EXTENSIONS, 'name': 'INI', 'loader': ini_loader},
            {'ext': ct.JSON_EXTENSIONS, 'name': 'JSON', 'loader': json_loader},
        ]

        // XXX custom loaders don't show up here since they're defined above
        for loader in loaders:
            if mod_file.endswith(loader['ext']):
                loader['loader'].load(
                    obj,
                    filename=mod_file,
                    env=env,
                    silent=silent,
                    key=key
                )
                continue
```
I don't see anywhere in the code that will allow my custom loader to find files in the search path which are defined by the extension setup in the custom loader.  Please help.

**Comment by rochacbruno** [comment]
This is not supported yet.

The current implementation reads YAML, TOML, INI, JSON by default at first and only after that it goes to read external loaders that you can add in `LOADERS_FOR_DYNACONF` list.

We need to implement a way to either change, or switch the default json encoder and/or library

**Comment by rochacbruno** [comment]
@fantapop fixed in https://github.com/rochacbruno/dynaconf/pull/133

For your use case you will need https://github.com/rochacbruno/dynaconf/tree/fix_122/example/flask_with_commentjson

only
```bash
pip install commentjson
```
then
```py
app = Flask(__name__)

FlaskDynaconf(app, COMMENTJSON_ENABLED_FOR_DYNACONF=True)
```

The disable of loaders also resolved.
