### ISSUE TITLE
Casting @bool should work on booleans

### ISSUE THREAD

**Issue by dbstraffin** [rochacbruno/dynaconf#14]
Currently, if I have `FOO = False` in settings.py` and I use `settings.get('FOO', cast='@bool')`, I get:
```
AttributeError: 'bool' object has no attribute 'lower'
```

I would suggest changing https://github.com/rochacbruno/dynaconf/blob/master/dynaconf/utils/parse_conf.py#L9 to:
```
'@bool': lambda value: True if str(value).lower() in true_values else False,
```

**Comment by rochacbruno** [comment]
good catch @dbstraffin going to implement your suggestion
