### ISSUE TITLE
Custom loader: what is the role of env variable in def load?

### ISSUE THREAD

**Issue by jacek-jablonski** [rochacbruno/dynaconf#148]
Hi,
according to documentation when implementing custom loader I should implement using this function:
```
def load(obj, env=None, silent=True, key=None):
```
However I have trouble understanding what is the point of env variable? For me it is always None, no matter what config environment is set.

**Comment by rochacbruno** [comment]
Hi @jacek-jablonski I'll take a look, this should receive the current_env being used.

Lets say user of app does `export ENV_FOR_DYANCONF=production` this variable should carry the `production` environment so you can use it to load the proper values.

If it is not there maybe it is a bug.

Today there will be a release and I'll include this issue,

**Comment by rochacbruno** [comment]
@jacek-jablonski thanks for reporting.

This is now fixed in https://github.com/rochacbruno/dynaconf/commit/0aa9670bed2f3df23bc279a7aa5f53e18c1a6c79

Will be part of 2.0.0 later today.

**Comment by jacek-jablonski** [comment]
Thanks for fixing!
