### ISSUE TITLE
[RFC] include pytest integration tests for Redis and Vault

### ISSUE THREAD

**Issue by rochacbruno** [rochacbruno/dynaconf#178]
Currently `Redis` and `Vault` features are skipped from unittests/coverage

https://github.com/rochacbruno/dynaconf/blob/b6ab9de2c7dfc1fe46dae2221d27b15534583503/.coveragerc#L11-L12

We are doing only `Functional` test cases by running the `example/` test cases.

https://github.com/rochacbruno/dynaconf/blob/b6ab9de2c7dfc1fe46dae2221d27b15534583503/Makefile#L82-L94

We need to evaluate this fixtures 
https://github.com/lovelysystems/lovely-pytest-docker 

and see if it works to have unittests for Redis and Vault.

**Comment by janw** [comment]
IMHO *unittests* should work without external fixtures and rather rely on mocking dependencies such as redis Redis or Vault. Maybe have a look at [`unittest.mock`](https://docs.python.org/3.7/library/unittest.mock.html)? That way you could ensure units are functional in itself, and keep the testsuite self-contained.

*Integration* tests are another topic of course. For those an "end-to-end" scenario with actual Redis and Vault instances would be desirable.

**Comment by rochacbruno** [comment]
You are right, I should've used "integration test"

We already have `functional test` it is on the examples folder and runs on every build.

I would like to have more detailed asserts using pytest style.. so integration tests.

I am not sure it is useful to mock those services (neither easy)

**Comment by hilam** [comment]
Working in this.
