### ISSUE TITLE
Error using multiple configs files from different folders, having a default file (not merged)

### ISSUE THREAD

**Issue by fabiosoft** [rochacbruno/dynaconf#182]
I need to read from multiple settings file and also a common setting file (aka defaults).
To do so i'm setting the ENV variable to the two file paths

```python
os.environ['SETTINGS_FILE_FOR_DYNACONF'] = '<abs_path>/config/default.toml, <abs_path>/config1/settings.toml'
```

default.toml
```ini
[development]
VAR_DFT = "default_dev"

[production]
VAR_DFT = "default_prod"
```

settings.toml
```ini
[development]
VAR1 = 'config1_dev'

[production]
VAR1 = 'config1_prod'
```

```python

import os
from dynaconf import settings

from config  import __file__ as config_file
from config1 import __file__ as config1_file
from config2 import __file__ as config2_file

default = os.path.join(os.path.dirname(config_file), 'default-settings.toml')
f1 = os.path.join(os.path.dirname(config1_file), 'settings.toml')
f2 = os.path.join(os.path.dirname(config2_file), 'settings.toml')

print('using config 1')
os.environ['SETTINGS_FILE_FOR_DYNACONF'] = "{}, {}".format(default, f1)

print('development')
settings.setenv('development')
print(settings.VAR_DFT) #no error
print(settings.VAR1) #gives me error

print('changing to production')
settings.setenv('production')
print(settings.VAR1)

print('----')

print('using config 2')
os.environ['SETTINGS_FILE_FOR_DYNACONF'] = "{},{}".format(default, f2)

print('development')
settings.setenv('development')
print(settings.VAR1)

print('changing to production')
settings.setenv('production')
print(settings.VAR1)

```

It gives me error `AttributeError: 'Settings' object has no attribute 'VAR1'` trying to access VAR1... so the more specific setting and not the default...
It seems like it's not merging the two configurations.

Is it possibile, am i totally on the wrong path?

**Comment by rochacbruno** [comment]
Please take a look on #183

**Comment by rochacbruno** [comment]
Dynaconf does not record the state of files between env changes.

Every time you call `setenv`, `usingenv`, `reload` all the loaded settings will be cleaned and the loading process will be executed again from the beginning.

To keep the state of the settings you want you need to use a `declarative` approach.

Use the same `SETTINGS_FILE` and switch using `INCLUDES`

Example added on #183

**Comment by rochacbruno** [comment]
The example on #183 may fix your problem,

We can go further and improve some dynaconf methods.

Do you think it would be useful to add this?

```python
settings.reload(includes=['a list of files'])
#and
settings.setenv('development', includes=['a list of files'])
```

**Comment by fabiosoft** [comment]
Very good example! From your comment it wasn't so clear, but the code seems to accomplish my needs!
As always you made an excellent tool.

A bit tricky is only the INCLUDES env variable format, maybe a `yaml` format doesn't need brackets and single quotes... but i don't know.

```python
os.environ["INCLUDES_FOR_DYNACONF"] = "['{}']".format(f1)  #"['config1/settings.toml']"
```

so probably a more python style reload/env/include would be useful... are you agree?

**Comment by rochacbruno** [comment]
@fabiosoft you are right about the formatting, that is  useful to environment variables complex lists but not for simple values.

I pushed the changes in #183 

- Now you can pass only the string filename as `path/to/path.toml` or separate it by `;` or `,`
- You can still pass a toml-like list
- You can use programmatically calling `settings.load_file(path="/path/to/file.toml")`
