### ISSUE TITLE
[bug] Regression: config file detection not working in subdir on ipython

### ISSUE THREAD

**Issue by PyUser5** [rochacbruno/dynaconf#184]
**Describe the bug**
When running a script from a subdirectory with ipython the `.env` is not found/evaluated in the parent dir.

**To Reproduce**

1. Having the following folder structure
```tree
.
├── subdir
│   └── test.py
└── test.py

```

2. Having the following config files:

<details>
<summary> Config files </summary>

**.env**
```bash
ENV_FOR_DYNACONF=PYTHON_WORKS_IPYTHON_DOES_NOT
```

</details>

3. Having the following app code:

<details>
<summary> Code </summary>

**test.py**  and **subdir/test.py**
```python
from dynaconf import settings
print(settings.ENV_FOR_DYNACONF)
```

</details>

4. Executing under the following environment

<details>
<summary> Execution </summary>

```bash
# conda install with python 3.7.3 and ipyhton 7.4.0 

$ python test.py        
PYTHON_WORKS_IPYTHON_DOES_NOT

$ python subdir/test.py 
PYTHON_WORKS_IPYTHON_DOES_NOT

$ cd subdir/

subdir$ python test.py        
PYTHON_WORKS_IPYTHON_DOES_NOT

subdir$ cd ..

$ ipython ./test.py 
PYTHON_WORKS_IPYTHON_DOES_NOT

$ ipython ./subdir/test.py   
PYTHON_WORKS_IPYTHON_DOES_NOT

$ cd subdir/

subdir$ ipython ./test.py 
DEVELOPMENT
```

</details>

**Expected behavior**
Last command should output PYTHON_WORKS_IPYTHON_DOES_NOT
(works with dynaconf 1.2.1)

**Environment (please complete the following information):**
 - OS: Linux/Ubuntu18.04
 - conda 4.6.14
 - python 3.7.3
 - ipython 7.4.0/7.5.0
 - Dynaconf Version 2.0.1/pip

**Comment by PyUser5** [comment]
inspect is working differently in ipython:
```ipython
In [3]: inspect.stack()[-1].filename                                                                                                                                                    
Out[3]: '/home/homedir/miniconda3/envs/myenv/bin/ipython'

```

```python
>>> inspect.stack()[-1].filename
'<stdin>'
```

**Comment by PyUser5** [comment]
in a script it returns in **ipython**:
```
/home/homedir/miniconda3/envs/myenv/bin/ipython
```


and in **python**:
```
./test.py
```

**Comment by rochacbruno** [comment]
Thanks for reporting, I am on it. The `find_files` needs to be enable to detect the call from REPL

**Comment by rochacbruno** [comment]
PR #190 opened with a fix for this issue.
