### ISSUE TITLE
[RFC] Allow dotted environment variables

### ISSUE THREAD

**Issue by CosmicMJ** [rochacbruno/dynaconf#197]
**Is your feature request related to a problem? Please describe.**
Parameters defined in environment variables cannot be accessed with dotted key notation in the same way as parameters defined in settings files, which prevents overriding dotted key parameters with environment variables. 

**Example:** Environment variable `DYNACONF_SERVICE_PORT` cannot be accessed via `settings['SERVICE.PORT']`. Instead, it must be accessed via `settings['SERVICE_PORT']`.

**Describe the solution you'd like**
One solution would be to use a designated sequence of characters to symbolize a dot separator, possibly two consecutive underscores ( `__` ). This character sequence could be configurable (eg `ENVVAR_DOT_SEPARATOR_FOR_DYNACONF`).

**Example:** Environment variable `DYNACONF_SERVICE__PORT` could be accessed via `settings['SERVICE.PORT']`, and would override any `service.port` parameter defined in a settings file.

**Describe alternatives you've considered**
An alternative to this could be to simply match either dotted or non-dotted key values to the correlated environment variable. As a note, this is how Spring Framework handles this feature.

**Example:** Environment variable `DYNACONF_SERVICE_PORT` could be accessed via `settings['SERVICE.PORT']` or via `settings['SERVICE_PORT']`, and would override any `service.port` or `service_port` parameter defined in a settings file.

**Additional context**
This would be especially nice for:
- allowing natural grouping of related settings (eg `service.host` and `service.port`)
- allowing overriding of existing parameters defined in a settings file
- accessing environment variables via object dot notation (eg `settings.SERVICE.PORT`)

**Comment by rochacbruno** [comment]
I like the idea, currently the alternative is to export variable using toml format.

```bash
export DYNACONF_SERVICE="{PORT='0.0.0.0'}"
```

This will write a `SERVICE` dictionary containing `PORT` and if dictionary already exists it is possible to add a `dynaconf_merge=true` to the same dict so it will be contributed but not overwritten.

I like the idea of having `__` (dunder) alternative, in the same way Django and other ORMs does.

**Comment by CosmicMJ** [comment]
> I like the idea, currently the alternative is to export variable using toml format.
> 
> ```shell
> export DYNACONF_SERVICE="{PORT='0.0.0.0'}"
> ```
> 
> This will write a `SERVICE` dictionary containing `PORT` and if dictionary already exists it is possible to add a `dynaconf_merge=true` to the same dict so it will be contributed but not overwritten.

Thanks, hadn't considered this option! I'll definitely use this as a short-term solution, though I think a more elegant solution is still needed.

> I like the idea of having `__` (dunder) alternative, in the same way Django and other ORMs does.

I think it'd be a good solution. It could potentially be configurable to use single underscores or dunders with a configuration key along the lines of `ENVVAR_DUNDER_SEPARATOR_FOR_DYNACONF` with a default value of `true`, which causes dynaconf to replace `.` with `__`, but when set to `false` causes dynaconf to replace `.` with `_` when doing lookups.

I really do think Spring handles this elegantly, as described by [this stackoverflow answer](https://stackoverflow.com/a/40612891/291323).
