### ISSUE TITLE
Cli tool 

### ISSUE THREAD

**Issue by rochacbruno** [rochacbruno/dynaconf#2]
a dynaconf cli to be use used on shell to validate and --help as documentation

**Comment by cuducos** [comment]
I'm interested in developing this! <3 CLI… but I'm nor sure about what _exactly_ this CLI should do, what kind of validations you have in mind? Check is a given variable is identified (and casted) by the package?

Another doubt: any pros and/or cons on working only with standard `argparse` (probably more lines of code) or adding a dependency on `docopt` (few lines of code)? As the project has no external dependency I'd opt for keeping only Python core modules (ie `argparse`)… but let me know if I'm missing anything.

**Comment by rochacbruno** [comment]
I was thinking about having something like.

## printing help
```bash
$ dynaconf --help
Thi is the Dynaconf help...
....
.... 
```

## validating a setting file

```bash
$ dynaconf --validate mysettings.py
........................................................................
Error: The value 'foo' attributed to MYVAR cannot be converted to @float
... 
```

## Generate settings from envvars
```bash
$ dynaconf --generate mysettings.py
"..wait while all environment variables started with DYNACONF_ is being written to mysettings.py..."

$ dynaconf --generate mysettings.py --namespace=PROJ1
"..wait while all environment variables started with PROJ1_ is being written to mysettings.py..."
```

**Comment by cuducos** [comment]
Sounds great! Gonna give it a shot one of these days!

**Comment by rochacbruno** [comment]
A lot of things changed @cuducos now Dynaconf can read from **redis** and other data stores. There is a need to write more client tools.

**Comment by cuducos** [comment]
Yes. I was going through your recent commits. I'm gonna code something today for Dynaconf, and once the CLI has the basics we can add more stuff. I'll send some xmas PR haha…

**Comment by cuducos** [comment]
This is my working branch for this issue, feel free to follow, comment, criticize, contribute etc:
https://github.com/cuducos/dynaconf/tree/cli

**Comment by rochacbruno** [comment]
:+1: 

Cool, I like argparse to avoid extra dependencies, but what do you think about click? http://click.pocoo.org/6/

**Comment by cuducos** [comment]
Ok, I've read about [Click](http://click.pocoo.org) but never tried. Let's try it then : )

**Comment by cuducos** [comment]
Just in case, new working branch (w/ click) https://github.com/cuducos/dynaconf/tree/cli-click
