### ISSUE TITLE
Document/Automate the Fedora packaging workflow

### ISSUE THREAD

**Issue by rochacbruno** [rochacbruno/dynaconf#201]
Thanks to @dmsimard dynaconf is being packaged for Fedora 31
https://koji.fedoraproject.org/koji/buildinfo?buildID=1336106

We need to put in place somewhere in the documentation the `how to update/release the packages after a new release is done`

we can also take a look on how to automate the process on Azure Pipelines CI

**Comment by dmsimard** [comment]
The source of the packaging is here: https://src.fedoraproject.org/rpms/dynaconf

**Comment by dmsimard** [comment]
FYI 2.2.0 will ship in the upcoming release of f31.
I somehow forgot to build the update for f30 so I did it just now and it'll land in a few days.

See: https://koji.fedoraproject.org/koji/packageinfo?packageID=29715

**Comment by rochacbruno** [comment]
I don think this issue is needed anymore,  I don't have plans  of maintaining other distributions than the PyPI one, there are  contributors packaging dynaconf for RPM,  AUR, DEB and others.
