### ISSUE TITLE
Document the use of pytest with dynaconf

### ISSUE THREAD

**Issue by dyens** [rochacbruno/dynaconf#203]
For testing in my project i want to add in my conftest.py something like that:

```
import pytest
import os

@pytest.fixture(scope='session', autouse=True)
def settings():
    os.environ['ENV_FOR_DYNACONF'] = 'testing'

```
But this is not work ;-(. What can you advise me ?
I dont want start my test like that : `ENV_FOR_DYNACONF=testing pytest` because somebody can miss that command prefix and mess up some dev data.

**Comment by dyens** [comment]
My solution:

```
import pytest
from dynaconf import settings

@pytest.fixture(scope='session', autouse=True)
def set_test_settings():
    settings.configure(ENV_FOR_DYNACONF='testing') 
```

**Comment by rochacbruno** [comment]
I am reopening this issue because I think we should add this to our documentation!

Thank you!

**Comment by kedark3** [comment]
@rochacbruno do you know if anyone working on this? If not, I can put up something!!

**Comment by rochacbruno** [comment]
for testing the `FORCE_ENV_DYNACONF` is useful will add to docs

**Comment by thomaszdxsn** [comment]
not work on Django LazySetting scenario

**Comment by rochacbruno** [comment]
@thomaszdxsn can you elabotare a bit more? what happens on Django?

**Comment by gabicavalcante** [comment]
@rochacbruno I think the maybe I have the same problem of this thread.
I have a variable on `[testing]` environment, and in my `conftest.py` I have:
```
@pytest.fixture(scope="session")
def app():
    app = create_app(FORCE_ENV_FOR_DYNACONF="testing")
    return app
```
In my app.py:
```
def create_app(**config):
    app = Flask(__name__)
    FlaskDynaconf(app, **config)
    ...
```

But when I tried to use the variable that I defined on `[testing]`, I got `AttributeError: 'Settings' object has no attribute '.....'`. Debugging the test code, I check the `settings.current_env` and it's 'DEVELOPMENT'. There are any way to start the tests loading `[testing]` environment?

**Comment by rochacbruno** [comment]
Hi @gabicavalcante here is what I have tried https://github.com/rochacbruno/dynaconf/pull/293 and I have not found any error.

Can you please see if your scenario has any difference from scenarios I included in https://github.com/rochacbruno/dynaconf/tree/issue_203/example/pytest_example

**Comment by gabicavalcante** [comment]
@rochacbruno I think that I found the problem. For example, my `.secrets.toml`: 
```
[default] 
TOKEN = "123"

[testing] 
TOKEN = "456"
``` 

my test:
```
from dynaconf import settings

def test_config(app):
   assert app.config.current_env == "testing" # OK
   assert app.config.TOKEN == "456" # OK

   assert settings.current_env == "testing" # ERROR
   assert settings.TOKEN == "456" # ERROR
```

I was trying to get the TOKEN using `settings.TOKEN`.

**Comment by rochacbruno** [comment]
@gabicavalcante got it!

When using FlaskDynaconf a new `Settings` object is binded to `app.config` then when you use `from dynaconf import settings` it is a different settings object separated from the Flask application.

**Comment by rochacbruno** [comment]
@gabicavalcante but, looks like we can fix it, make the `FlaskDynaconf` to also set the `dynaconf.settings` so references  will point to the same object and avoid conflicts.

I will check if it is thread safe to do this.

**Comment by rochacbruno** [comment]
@gabicavalcante I updated the PR and made `dynaconf.settings` to be always inded to `app.config` so you can use both and this confusion will not happen again, thanks for the insight.

@thomaszdxsn I think the PR also solves the Django problem.
