### ISSUE TITLE
Empty Configuration options on the Configuration page

### ISSUE THREAD

**Issue by VaultVulp** [rochacbruno/dynaconf#204]
Looks like I've messed something on a [configuration page](https://dynaconf.readthedocs.io/en/latest/guides/configuration.html#configuration-options) in my PR #202 .

**To Reproduce**

Visit [configuration page](https://dynaconf.readthedocs.io/en/latest/guides/configuration.html#configuration-options), and check that there is no table after the `Configuration options` header.

I'll try to fix this ASAP, sorry for the inconvenience.

**Comment by rochacbruno** [comment]
@VaultVulp no problem, we can fix that.

Also That table is a pain to maintain, i would like to come with a different and more maintainable way of formatting a table there. If you have any idea.

**Comment by rochacbruno** [comment]
@VaultVulp BTW: I was using a VSCode extension that autoformats .rst tables.

**Comment by VaultVulp** [comment]
@rochacbruno Tried to provide a fix for this table in the #205.

I've also spend quite a bit of time tweaking with the table and still (as you see) messed something inside of it. I have another idea for a contribution, but I'll think about a better way to keep this table consistent with the code base.
