### ISSUE TITLE
Improve or replace the configuration reST table

### ISSUE THREAD

**Issue by rochacbruno** [rochacbruno/dynaconf#206]
## Problem

This page https://dynaconf.readthedocs.io/en/latest/guides/configuration.html
has a table that is written using reST syntax https://github.com/rochacbruno/dynaconf/blob/master/docs/guides/configuration.md#configuration-options

this table is very difficult to maintain, it is not easy to add new options and it is also not responsive.

## Wanted solution

- A table that is easy to maintain (to add new options)
- A table that can be responsive on mobile devices.

## Ideas

- Have all that data set in a YAML file or a simple python dictionary
- Then use that data to generate the table when the docs are generated
- Use some css/js skill to make searchable, collapsible, responsive

> **Any ot her ideas are welcome**

**Comment by rochacbruno** [comment]
Tolls that can be used

https://github.com/mplewis/csvtomd

**Comment by dgarcia360** [comment]
Hi @rochacbruno, you could use the native [csv-table directive](http://docutils.sourceforge.net/docs/ref/rst/directives.html#id4) from restructuredText. 

```eval_rst
.. csv-table::
    :header: "Variable", "Type", "Usage", "default", "envvar example"
    :widths: 10 10 30 25 25
    :delim: ;

    ROOT_PATH; str; Directory to look for settings files. This path is the base to search for files defined in *SETTINGS_FILE* Dynaconf will also search for files in a relative config/ subfolder if exists.; *None* If set Dynaconf will look this path first before it starts to search for file in the other locations. see: `<usage.html#the-settings-files>`_; ROOT_PATH_FOR_DYNACONF=”/my/custom/absolute/path/”
    (...)
```

As dynaconf docs are written in Markdown, the directive should be wrapped in a ``eval_rst`` block.

If the solution proposed looks ok, I'd be happy to submit the PR 👍

**Comment by rochacbruno** [comment]
@dgarcia360 looks nice! and easier to edit the table.

I like it! :)

**Comment by dyens** [comment]
You can edit  table in org file by emacs like (https://www.youtube.com/watch?v=5vGGgfs0q3k) using [org mode](https://orgmode.org/).
And then it can be converted to md or another format.
