### ISSUE TITLE
[bug]Clean Python pip install problem

### ISSUE THREAD

**Issue by bwacek** [rochacbruno/dynaconf#230]
**Describe the bug**
If starting a new Python installation, DynaConf 2.1.0 will not work successfully.  It appears to be choking while reading a YAML file.  The only workaround I have found is to roll back to 2.0.4.

**To Reproduce**
I have put together a very simple project that will demonstrate the problem, see the attached zip file below.  Just make sure you are using a brand new installation of Python - System, VirtualEnv or Conda Environment - problem occurs in all cases.  Just for clarity, I use Conda.

pip install -r requirements.txt
python dc-error.py

**Expected behavior**
The program should run and print out the setting from the error.yaml file.

**Debug output**
C:\ProgramData\Anaconda3\envs\DynaConfError\python.exe C:/Development/DynaConfError/dc-error.py
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\DynaConfError\lib\site-packages\dynaconf\loaders\base.py", line 110, in _read
    data = source_data[env.lower()]
KeyError: 'dynaconf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Development/DynaConfError/dc-error.py", line 11, in <module>
    settings.load_file(path='error.yaml', silent=False)
  File "C:\ProgramData\Anaconda3\envs\DynaConfError\lib\site-packages\dynaconf\base.py", line 908, in load_file
    filename=path,
  File "C:\ProgramData\Anaconda3\envs\DynaConfError\lib\site-packages\dynaconf\loaders\__init__.py", line 116, in settings_loader
    obj, filename=mod_file, env=env, silent=silent, key=key
  File "C:\ProgramData\Anaconda3\envs\DynaConfError\lib\site-packages\dynaconf\loaders\yaml_loader.py", line 50, in load
    loader.load(filename=filename, key=key, silent=silent)
  File "C:\ProgramData\Anaconda3\envs\DynaConfError\lib\site-packages\dynaconf\loaders\base.py", line 71, in load
    self._read(files, env_list, silent, key)
  File "C:\ProgramData\Anaconda3\envs\DynaConfError\lib\site-packages\dynaconf\loaders\base.py", line 125, in _read
    raise KeyError(message)
KeyError: 'yaml_loader: dynaconf env not defined in C:\\Development\\DynaConfError\\.\\error.yaml'

**Environment (please complete the following information):**
 - OS: Windows 10 Pro, Ubuntu 18.04, CentOS 7
 - Dynaconf Version 2.1.0
 - Frameworks in use:  None

**Additional context**
Interestingly, if you already had an older version of DynaConf installed in a python environment and update it, this code will execute and work as expected.

[DynaConfError.zip](https://github.com/rochacbruno/dynaconf/files/3598272/DynaConfError.zip)

**Comment by rochacbruno** [comment]
This is the expected behavior if you load using `silent=False` this makes dynaconf to raise all the internal errors, in this case your settings file doesn't have all the possible environments.

Change it to Silent=True or remove this parameter as `silent=True` is the default

```py
from dynaconf import LazySettings

# This is an easy way to get around having to have an.env file to set this environmental variable.  It's a
# DynaConf thing...
#   Env Files:  https://dynaconf.readthedocs.io/en/latest/guides/usage.html#the-settings-files
#   This workaround:  https://dynaconf.readthedocs.io/en/latest/guides/configuration.html
settings = LazySettings(
    ROOT_PATH_FOR_DYNACONF='.',
)

settings.load_file(path='error.yaml', silent=True)
print(settings['var_1'])

```

**Comment by rochacbruno** [comment]
I will keep this open as this may be documented under `advanced usage` doc guide.
