### ISSUE TITLE
[RFC] Rewrite docs using MkDocs

### ISSUE THREAD

**Issue by rochacbruno** [rochacbruno/dynaconf#246]
1. Remove Sphinx
2. MIgrate to Mkdocs
3. Use https://github.com/tomchristie/mkautodoc
4. Rewrite docs (rearrange it)
5. Make it in a way that the current docs redirects to the new
6. Check if readthedocs.. can support mkdocs

**Comment by jperras** [comment]
What's the issue you're experiencing with Sphinx?

**Comment by rochacbruno** [comment]
@jperras 

I really like Markdown and I think it is better for people who wants to contribute with docs.

and I saw documentations like this https://fastapi.tiangolo.com/ and looks really great and better organized.

**Comment by rochacbruno** [comment]
https://github.com/pawamoy/mkdocstrings
