### ISSUE TITLE
Is it a good idea to store class instance reference into dynaconf ?

### ISSUE THREAD

**Issue by tux-00** [rochacbruno/dynaconf#255]
I think the answer is no but I was searching how dynaconf persist settings across import in multiple files and I don't found the answer.

Example:
```
settings.set("CLASSES.database", Database())
```

The advantage is the code simplification because I do not need to pass the instance on every classes of my project.

Maybe it's dangerous due to the garbage collector ?

Sorry if that seems like a stupid question but I can't found a real answer on the web (I found some python module like weakref, pickle etc... but does not seem to do the trick properly).

PS: I love your work, I can now remove a lot of configparser code and improve readability !

**Comment by rochacbruno** [comment]
@tux-00 not a good idea

dynaconf supports only the formats that can be serialized/de-serialized from specific file, for example, to load/write json files the data must be JSONable.

**Comment by rochacbruno** [comment]
@tux-00 however..

If you really need,

You can write a custom loader that will write a pickle with your settings and then load from this pickle.

Dynaconf does not have a pickle loader yet.

HOw to write your loader -> https://dynaconf.readthedocs.io/en/latest/guides/extend.html
