### ISSUE TITLE
[bug] Testing and mocking docs are wrong

### ISSUE THREAD

**Issue by anxodio** [rochacbruno/dynaconf#264]
**Describe the bug**
The docs in https://dynaconf.readthedocs.io/en/latest/guides/testing.html explain how to test with dynaconf. The point is that if you follow the explanation, you will see `AttributeError: 'DynaconfDict' object has no attribute 'current_env'`

**To Reproduce**

Just try to follow the steps in https://dynaconf.readthedocs.io/en/latest/guides/testing.html

**Expected behavior**
The code don't fail and the mock can be used.

**Debug output**

<details>
<summary> Debug Output </summary>

```bash
Traceback (most recent call last):
  File "lalala.py", line 5, in <module>
    toml_loader.load(mocked_settings, filename="test_conf.toml", env="testing")
  File "/home/angel/.virtualenvs/navi-Pag0EvBg/lib/python3.6/site-packages/dynaconf/loaders/toml_loader.py", line 38, in load
    loader.load(filename=filename, key=key, silent=silent)
  File "/home/angel/.virtualenvs/navi-Pag0EvBg/lib/python3.6/site-packages/dynaconf/loaders/base.py", line 69, in load
    env_list = build_env_list(self.obj, self.env)
  File "/home/angel/.virtualenvs/navi-Pag0EvBg/lib/python3.6/site-packages/dynaconf/utils/__init__.py", line 220, in build_env_list
    if obj.current_env and obj.current_env not in env_list:
AttributeError: 'DynaconfDict' object has no attribute 'current_env'
```

</details>

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Dynaconf Version 2.2

**Comment by rochacbruno** [comment]
We need to add a `current_env` property here

https://github.com/rochacbruno/dynaconf/blob/6bd9d8b88803690117e5cb5b14388da8b8011d91/dynaconf/utils/__init__.py#L52-L72

**Comment by rochacbruno** [comment]
```diff
def __init__(self, *args, **kwargs):
        self._loaded_files = []
+       self.current_env = kwargs.get('env', 'development')
        super(DynaconfDict, self).__init__(*args, **kwargs)

```

**Comment by hilam** [comment]
I will work on this.

**Comment by hilam** [comment]
@rochacbruno Your suggestion results in another error. Any other ideas? I'm trying to figure out.

Traceback (most recent call last):
  File "/home/hilam/other-projects/dynaconf/dynaconf/loaders/base.py", line 69, in load
    env_list = build_env_list(self.obj, self.env)
  File "/home/hilam/other-projects/dynaconf/dynaconf/utils/__init__.py", line 232, in build_env_list
    return [env.lower() for env in env_list]
  File "/home/hilam/other-projects/dynaconf/dynaconf/utils/__init__.py", line 232, in <listcomp>
    return [env.lower() for env in env_list]
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by rochacbruno** [comment]
@hilam maybe

```py
self.current_env = kwargs.get('env') or 'development'
```

**Comment by sinnedh** [comment]
We have the same issue here with additional accessors as `as_dict` or `as_int` here:
```
AttributeError: 'DynaconfDict' object has no attribute 'as_int'
```

**Comment by rochacbruno** [comment]
I think it is time to reimplement the `DynaconfDict` in a way that it inherits from `Settings` and overrides some methods to avoid unwanted loads under testing environment.

**Comment by hilam** [comment]
During my attempts to solve it, I tried to inherit from Settings or LazySettings, but it didn't work. Mysterious import errors. As you know the code better, @rochacbruno  you may be able to find the solution. I could not.

**Comment by ximet** [comment]
have the same issue. How I can help with it?

**Comment by rochacbruno** [comment]
This is a pending issue, we still need a way to have DynaconfDict to be an instance of  `Dynaconf` class or a subclass of it.

Probably we can deprecate the DynaconfDict (alias it to a new  class)

**Comment by mazzi** [comment]
Nice insight!
@rochacbruno So actually there's no way to mock settings?
I was digging in the tests but didn't find anything to load a json or a dict and being able to mock tests.
Thanks!

**Comment by arugifa** [comment]
@mazzi In fact, MonkeyPatching Dynaconf settings in Pytest doesn't work, unfortunately. Setting values don't change that way.

**Comment by limdauto** [comment]
I think the easiest way is to dump a settings file to a temporary location and load it. Something like:

```python
@pytest.fixture
def mock_settings_path(tmpdir):
    settings_path = tmpdir.mkdir("test_package").join("settings.py")
    settings_path.write(
        textwrap.dedent(
            f"""
                SETTING_ONE = True
            """
        )
    )
    return str(settings_path) 
```

And you can use the fixture as follows:

```python
def test_settings_file(mock_settings_path):
    settings = LazySettings(settings_file=mock_settings_path)
    assert SETTING_ONE == True
```

The beauty of this approach is that you can actually add a `Mock` to your mock settings file, e.g.

```
# in your test module
MOCK_SETTING_TWO = MagicMock()

# in your mock settings file
f"""
from {__name__} import MOCK_SETTING_TWO
SETTING_TWO = MOCK_SETTING_TWO
"""
```

**Comment by GerardoGR** [comment]
I haven't had a closer look to the code to see the inner workings of this, but initializing and mocking the object like this:

```python
from unittest.mock import patch

from dynaconf import Dynaconf

from my_module impoprt function_name


@patch("config.settings", Dynaconf(log_level="DEBUG"))
def test_patch(self):
    assert function_name() == "DEBUG"
```

Gives the expected result when trying to access the object like `settings.log_level` or `settings["log_level"]`
