### ISSUE TITLE
[bug] Dynaconf does not support null values in yaml

### ISSUE THREAD

**Issue by Bahus** [rochacbruno/dynaconf#288]
**Describe the bug**
If you specify a null value for a variable in a yaml config file and when you try to use this variable you will get "variable does not exists" error.

The same issue should appear when using nulls in vault (since it's a JSON).

**To Reproduce**
The following python snippet can be used to reproduce the issue:

```python
from dynaconf.base import Settings
settings = Settings()
settings['name'] = 'Hello'
settings['nulled_name'] = None

print(settings['name'])
print(settings['nulled_name'])
```

The output is:

```
Hello
Traceback (most recent call last):
  File ".../dynaconf/base.py", line 222, in __getitem__
    raise KeyError("{0} does not exists".format(item))
KeyError: 'nulled_name does not exists'
```

**Comment by lobocode** [comment]
I believe this has something to do with the version of YAML used in dynaconf. The Null value in Yaml can be expressed with `null`,` ~ `. If you use `settings ['nulled_name'] = None`, you are using Python values ​​to set null to YAML. That is, the syntax is incorrect. However, even using the correct syntax, it will not work. In this case, try to use `settings['nulled_name'] = " "` https://yaml.org/type/null.html .

**Comment by Bahus** [comment]
@lobocode hi, the "to reproduce" section script shows the problem in the dynaconf core, which in turns affects how dynaconf parses YAML configs (you can reproduce it with `value: null` or `value: ~` in an arbitrary YAML file). I don't really wan't to replace nullable values with spaces, since it may lead to unintended consequences in my application.
