### ISSUE TITLE
Project is missing documentation?

### ISSUE THREAD

**Issue by vladcalin** [rochacbruno/dynaconf#29]
I couldn't find any documentation for this project.
I suggest to generate (with sphinx, using autodoc plugin?) some documentation for the end user and for future people that are interested in contributing to this project (for example I couldn't find some hints or guides on how to create a loader from scratch).

**Comment by vladcalin** [comment]
@rochacbruno  I'll be more than glad to take care of this! :smile:

**Comment by vladcalin** [comment]
I just opened a PR for this: https://github.com/rochacbruno/dynaconf/pull/30 .  Let me know if you have other ideas for the documentation.

**Comment by renzon** [comment]
Yeah, I was in doubt about how to change loaders precedence before talking to @rochacbruno

**Comment by marcominas** [comment]
How can I help with the project documentation?

**Comment by vladcalin** [comment]
Then I'm closing this issue since it was resolved.
