### ISSUE TITLE
[question] Which is the proper way to make a library settings "overrideable" ?

### ISSUE THREAD

**Issue by danielmartins** [rochacbruno/dynaconf#294]
Hi, 

First, thanks for this amazing lib. 

I don't know if is a bug or wrong usage, so, I'm trying to give some details with code examples. 

Consider the follow application structure:
```
example_project/
  -> main_application/
      -> __init__.py
      -> main.py
      -> settings.yaml
  -> library/
      -> __init__.py
      -> awesome.py
      -> settings.yaml
```
The file contents are:

main.py
```python
from library.awesome import amazing_function

if __name__ == "__main__":
    amazing_function()
```
awesome.py
```python
from dynaconf import settings


def amazing_function():
    print(settings.TO_OVERRIDE_CONF)


if __name__ == "__main__":
    amazing_function()
```

main_application/settings.yaml
```yaml
default:
  TO_OVERRIDE_CONF: "b"
```

library/settings.yaml
```yaml
default:
  TO_OVERRIDE_CONF: "a"
```

When I execute main.py will print: **"b"**

If I delete/rename main_application/settings.yaml and execute again I will get an exception:

```
AttributeError: 'Settings' object has no attribute 'TO_OVERRIDE_CONF'
```

I was expecting to get **"a"** from library/settings.yaml or am I terribly wrong ? :thinking: 

I've made some attempts to get this behavior, wrapping settings module to use LazySettings.

Consider following:

+ Add main_application/configurator.py
```python
from os.path import dirname

from dynaconf import LazySettings
import library

lib_settings_abs_path = dirname(library.__file__) + "/" + "settings.yaml"

settings = LazySettings(
    DEBUG_LEVEL_FOR_DYNACONF="DEBUG",
    PRELOAD_FOR_DYNACONF=[lib_settings_abs_path],
)

```

then change the main_application/main.py to
```python
from library.awesome import amazing_function
from main_application.configurator import settings

if __name__ == "__main__":
    print(settings.TO_OVERRIDE_CONF)
    amazing_function()

```

I'll get printed **"a"** from library/settings.yaml, which is nice, but amazing_function() will raise an the **AttributeError** exception. :cry:. Why they do not consider look the settings.yaml beside him as last resource ?

And with this approach, If a restore main_application/settings.yaml wich contains **"b"** on **TO_OVERRIDE_CONF** I got:

```
a
b
```
Which is **a** from **settings.TO_OVERRIDE_CONF** and **b** from **amazing_function()**, this confused me. 
I was expecting to get **b** from **settings.TO_OVERRIDE_CONF** because of main_application/settings.yaml is in place and the arg **PRELOAD_FOR_DYNACONF** preloaded the library/settings.yaml, but the local main_application/settings.yaml should override the preloaded one, is that right :thinking: ?

Added the files to a repo to make easy to reproduce: https://github.com/danielmartins/dynaconf_samples

**Comment by rochacbruno** [comment]
This is related to #299 and still needed, it is possible right now but we   need a better/documented  way
