### ISSUE TITLE
Cant load settings file in chalice application

### ISSUE THREAD

**Issue by kj96** [rochacbruno/dynaconf#295]
Hi, I am trying to use dynaconf to load config file in a chalice application

I have this folder structure:

```
chalice_app
└── .env
└── app.py
└── chalicelib
    ├── config
    ├── main.py
    └── settings.toml
```
in app.py:
```

#app.py
from dynaconf import settings

print(settings["APP_NAME"])
```

and settings.toml:
```

#settings.toml
[default]
APP_NAME="chalice_app"
```

I tried defining `SETTINGS_FILE_FOR_DYNACONF` and `APP_NAME` in `.env`

`SETTINGS_FILE_FOR_DYNACONF=chalicelib/settings.toml`

But its not able to find `APP_NAME `
Also its not able lo load `.env` from _root directory_ or from `chalicelib`

**Comment by rochacbruno** [comment]
Hi @kj96 I never used chalice so I need more info to reproduce this issue, how the app is started?

**Comment by kj96** [comment]
@rochacbruno This can be reproduced by creating simple chalice app. Its very much similar to Flask.

**To Reproduce** 
Create a new chalice app
`chalice new-project chalice-dynaconf-test`

It will create a folder with project name _chalice-dynaconf-test_

```

chalice-dynaconf-test/
|
├── .chalice/
│   └── config.json
|
├── .gitignore
├── app.py
└── requirements.txt
```


**app.py**
```
from chalice import Chalice

app = Chalice(app_name='chalice-dynaconf-test')

@app.route('/')
def index():
    return {'hello': 'world'}
```

The **app.py** file contains all of your view functions and route information

Chalice documentation: https://chalice.readthedocs.io/en/latest/quickstart.html

**Config file**
Now to add more python file, config files or directory **chalicelib/** directory should be created, and anything in that directory is recursively included in the deployment package.

So I added .env config in root and chalicelib
```

chalice-dynaconf-test/
|
├── .chalice/
│   └── config.json
├── .chalicelib/
│   └── .env
|
├── .env 
├── .gitignore
├── app.py
└── requirements.txt
```

Updated app.py
```
from chalice import Chalice
from dynaconf import settings

app = Chalice(app_name='chalice-dynaconf-test')

print(settings.colors)

@app.route('/')
def index():
    return {'hello': 'world'}

```

.env
```
[default]
colors = ["green", "blue"]
parameters = {enabled=true, number=42}
App_Name = CHALICE_DYNACONF_TEST
```

To run locally on computer:
**chalice local**

**Comment by Dev-Root2IoT** [comment]
Hello... Facing similar issue, Has someone made any progress ?

**Comment by dcifuen** [comment]
https://github.com/dcifuen/chalice-dynaconf-helloworld

**Comment by rochacbruno** [comment]
That is great @dcifuen we need to add this to the docs, I will include a new section in the docs for those kind of examples.

**Comment by rochacbruno** [comment]
We need an update  for this for dynaconf 3.0 style  (using Dynaconf class instead of dynaconf.settings object)

**Comment by rochacbruno** [comment]
also we  need:

- include the example to the docs
- include a running example to the example/ folder
- run that on CI
