### ISSUE TITLE
Vendoring dependencies? 

### ISSUE THREAD

**Issue by rochacbruno** [rochacbruno/dynaconf#301]
Recently python-box broke and also we had to pin python-dotenv, so given the way dynaconf is embedded on libraries and applications looks like a good idea to vendor 3 libs.

- toml
- python-box
- python-dotenv
- click

**Comment by rochacbruno** [comment]
maybe replace box with a simpler implementation.

**Comment by pavel-razgovorov** [comment]
Hello.

I stumbled upon your project and wondered: why would you rather have your dependencies "vendored" (that is, to keep a full copy of them inside this repo) instead of using a dependency management tool? If you have some time to answer this please let me know because I am curious about the reasoning to do so.

**Comment by rochacbruno** [comment]
Hi @pavel-razgovorov 

That decision was made because dynaconf started being packaged for many O.S including debian, RHEL, Arch.

To enable dynaconf to be a .rpm package for example it would require also the packaging of every dependency individually, so we decided to vendor it (the same way other projects does ex. https://github.com/pypa/pipenv/tree/master/pipenv/vendor for the same reason)

**Comment by rochacbruno** [comment]
NOTE: The `vendor_src` is where the full copy is kept

The `vendor` contains a minified version to save disk space.

**Comment by Apteryks** [comment]
On some system such as Debian and GNU Guix, vendoring or bundling is against the packaging policy, so this won't help.  No matter how you look at it, bundled dependencies are almost always a bad idea and is akin to technical debt (what happens the day a bundled dependency is no longer supported by the current Python?  You are either forced to do a large maintenance sprint to update them, or do development on the old bundled copies to bring them to compatibility).

**Comment by rochacbruno** [comment]
@Apteryks once Python gets builtin TOML and YAML I am open to write a builtin implemention of Box and then remove all other dependencies.

**Comment by rochacbruno** [comment]
@Apteryks vendoring is common on python projects, `pip` for example has some libraries vendored. As long as the licenses permits it is allowed.

**Comment by gotmax23** [comment]
> once Python gets builtin TOML and YAML I am open to write a builtin implemention of Box and then remove all other dependencies.

Python 3.11 and above have tomllib. I don't see the problem with external dependencies on tomli or pyyaml/ruamel.yaml.

**Comment by rochacbruno** [comment]
@gotmax23 this is going to change on the release 4.0, not sure when, but 4.0 will be a metapackage `pip install dynaconf` will bring [`dynaconf-core`, `dynaconf-toml`, `dynaconf-yaml`, `dynaconf-jinja`, etc..`]  so there will be some plugins and each plugin will bring its own deps.

**Comment by gotmax23** [comment]
> each plugin will bring its own deps.

What do you mean by "bring its own deps?" Will those be vendored?

**Comment by rochacbruno** [comment]
@gotmax23 for the plugins under the dynaconf/ org it will no more vendor anything, for external plugins it will depend on plugins.
