### ISSUE TITLE
Move to Poetry for dev environment and build?

### ISSUE THREAD

**Issue by rochacbruno** [rochacbruno/dynaconf#302]
Any advantage on moving dynaconf to Poetry? do we still need a `setup.py` available?

**Comment by kuwv** [comment]
The pyproject.toml was designed to solve the chicken / egg build problem setuptools has: https://www.python.org/dev/peps/pep-0518/

This pep did not provide scope for other subsystems to be integrated. So, migrating to poetry will depend on if having multiple tool configuration files is fine. 

I think this should provide context: https://github.com/python/mypy/issues/5205#issuecomment-396629530

**Comment by rochacbruno** [comment]
@kuwv I am also taking a look at PyFlow which looks very interesting, Poetry has some limitation to work in editable mode.

**Comment by rochacbruno** [comment]
Not  needed anymore, all deps are vendored
