### ISSUE TITLE
[bug] Dynaconf list is showing the class notation not the value

### ISSUE THREAD

**Issue by rochacbruno** [rochacbruno/dynaconf#305]
**Describe the bug**
When using `dynaconf list` having lazy values, the out put is the class notation instead of the formatted value.

**To Reproduce**

Export a variable using a lazy formatter

```bash
export DYNACONF_PATH="@format /databases/{env[USER]}"
```

On the console run `dynaconf list`

```
dynaconf on  master [$] via 🐍 v3.7.0(dynaconf) 
❯ dynaconf list                                        
Working in development environment 
USERNAME: 'RiverFount'
DAY: 28.0
PATH: <dynaconf.utils.parse_conf.LazyFormat object at 0x7fe
68fecc898>
```

What is the actual result.

```
PATH: <dynaconf.utils.parse_conf.LazyFormat object at 0x7fe
68fecc898>
```

What I expected to see

```
PATH: "@format /databases/{env[USER]}"
```

**Comment by rochacbruno** [comment]
https://github.com/rochacbruno/dynaconf/blob/fd9622dd46a5261c243f29eadb43d997f17e408e/dynaconf/utils/parse_conf.py#L55-L72

**Comment by kshahar** [comment]
In addition, running `dyanconf list -o test.json` results in a TypeError exception:
```
TypeError: Object of type 'LazyFormat' is not JSON serializable
```

To reproduce:
```
(export DYNACONF_TEST="@format test"; dynaconf list -o out.json)
```
