### ISSUE TITLE
[bug] Settings merged instead of replaced

### ISSUE THREAD

**Issue by dkliban** [rochacbruno/dynaconf#306]
The issue was initially filed against, Pulp. But I believe this is a dynaconf problem. 

https://pulp.plan.io/issues/6244

**Comment by rochacbruno** [comment]
Having a `settings.py` with

```py
BASE = {"CLASSES": ["class1", "class2"]}
```

User should be able to override the whole "CLASSES" key by doing:

```bash
export DYNACONF_BASE__CLASSES="['other1', 'other2']"
```
ending with `BASE = {"CLASSES": ["other1", "other2"]}`

User should be able to merge values by using `@merge` mark

```bash
export DYNACONF_BASE__CLASSES="@merge ['other1', 'other2']"
```
ending with `BASE = {"CLASSES": ["class1", "class2, "other1", "other2"]}`

**BUT** looks like dynaconf is defaulting to `@merge` behavior.

**Comment by rochacbruno** [comment]
PR #315 sent

@dkliban @daviddavis I figured out it was not a bug, but the intended behavior. 

Although it was a bad design decision so I reverted and now it is going to default o `reasign` and merge only when variable explicitly starts with `@merge ` 

This is a breaking change so I will release it as part of 3.0.0 by the end of the month.

Do you need it earlier?

**Comment by daviddavis** [comment]
@rochacbruno thanks for the update. That all makes sense. I'll check with Katello on when they need it and get back to you.
