### ISSUE TITLE
examples.md .env section - DYNACONF prefix missing?

### ISSUE THREAD

**Issue by kshahar** [rochacbruno/dynaconf#308]
In [examples.md under .env](https://github.com/rochacbruno/dynaconf/blob/44ac11b2cb95396af5646a2ac36ecedae5321dfd/docs/guides/examples.md#env) the environment variables do not have a prefix. Is the DYNACONF prefix missing or does this assume `ENVVAR_PREFIX=false` is defined?

**Comment by rochacbruno** [comment]
you are right, prefix is needed there
