### ISSUE TITLE
[bug] POSIX permissions preventing access to settings file fail silently

### ISSUE THREAD

**Issue by bmbouter** [rochacbruno/dynaconf#310]
I put a config file at `/etc/pulp/settings.py` and I indicate to Pulp on this specific system to use it with the envvar `PULP_SETTINGS="/etc/pulp/settings.py"`. Note my user does not have POSIX read permissions to `/etc/pulp/` itself. Pulp configured dynaconf to use `PULP_` as its envvar prefix.

When using `dynaconf list` your settings don't apply and that passes silently. If the user configures a specific file and you cannot read it I expect an error to be raised, or if the file is missing or empty at least a warning.

**Comment by rochacbruno** [comment]
Still considering this issue

- I want it to be optional
- When instantiating `Dynaconf` class it should be enabled via  an option such as `raise_for_filesystem=True`

The default behavior will still be: `if file cannot be read it is not loaded`
