### ISSUE TITLE
[bug] Little bug on docs/customexts with variable undeclared.

### ISSUE THREAD

**Issue by Bernardoow** [rochacbruno/dynaconf#320]
**Describe the bug**
I read the code and on file docs/customexts/aafig.py and on the line 120 is used one variable **text** and this variable wasn't created before.

[Link to file](https://github.com/rochacbruno/dynaconf/blob/bb6282cf04214f13c0bcbacdb4cee65d4c9ddafb/docs/customexts/aafig.py#L120)

`img.replace_self(nodes.literal_block(text, text))`

```python
def render_aafig_images(app, doctree):
    format_map = app.builder.config.aafig_format
    merge_dict(format_map, DEFAULT_FORMATS)
    if aafigure is None:
        app.builder.warn('aafigure module not installed, ASCII art images '
                'will be redered as literal text')
    for img in doctree.traverse(nodes.image):
        if not hasattr(img, 'aafig'):
            continue
        if aafigure is None:
            img.replace_self(nodes.literal_block(text, text))
            continue
        options = img.aafig['options']
        text = img.aafig['text']
```

**Comment by rochacbruno** [comment]
Probably we are going to remove this aafig and all sphinx soon when we move to Mkdocs #246
