### ISSUE TITLE
[RFC] Merge all settings files before merging defaults and environment settings

### ISSUE THREAD

**Issue by tjader** [rochacbruno/dynaconf#322]
**Is your feature request related to a problem? Please describe.**
Currently, a default setting from settings.local.yaml takes precedence over an environment-specific setting in settings.yaml. To me, the intuitive behaviour would be that default settings in settings.local.yaml only would be used if no environment-specific setting has already been set.
```
# settings.yaml
default:
  key: default-from-settings

development:

production:
    key: production-from-settings
```

```
# settings.local.yaml
dynaconf_merge: true
default:
    key: default-from-local
```
In the above example, the key would always be "default-from-local".
**Describe the solution you'd like**
To me, a more useful behaviour would be to have key be "default-from-local" only when the development setting, but the production value would still remain "production-from-settings".

**Additional context**
The current behaviour is to individually merge each files default settings with environment specific settings first, then to merge the files together. I propose that the behaviour changes to first merge all files together, then merge default settings with the environment-specific settings.

**Comment by rochacbruno** [comment]
This requires a big change on how loaders are implemented,

This is related to #245 

I  want to try a https://docs.python.org/3/library/collections.html#collections.ChainMap implementation for the loaders chaining files and environments

**Comment by rochacbruno** [comment]
@aberres comment here: https://github.com/rochacbruno/dynaconf/issues/284#issuecomment-638095698  is related to this issue.
