### ISSUE TITLE
template substitutions not applied to nested values

### ISSUE THREAD

**Issue by davegaulke** [rochacbruno/dynaconf#324]
I'm using dynaconf 3.0.0rc1 with python 3.8.1. When using template substitutions in a value that is nested below a map, the substitution is not performed on access.  A simple example is below. I don't know if this is expected behavior or not. Are template substitutions only supported at the top-level?

```
$ cat settings.toml:
[default]
    foo = "@format {env[MYVAR]}"
[default.path]
    foo = "@format {env[MYVAR]}"
$ export MYVAR=xyz 
$ python           
Python 3.8.1 (default, Mar 18 2020, 14:11:39) 
[GCC 9.3.1 20200317 releases/gcc-9.3.0-37-g65de83595f] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from dynaconf import settings
>>> print ( settings.FOO )
xyz
>>> print (settings.PATH.foo)
<dynaconf.utils.parse_conf.LazyFormat object at 0x7fb2d2069160>
```

**Comment by rochacbruno** [comment]
Hi @davegaulke it is supposed to work on all values in any level, looks like a bug, thanks for reporting.

**Comment by rochacbruno** [comment]
Fixed in master, will be in nest release
