### ISSUE TITLE
How to override this var?

### ISSUE THREAD

**Issue by heckad** [rochacbruno/dynaconf#330]
I have such settings.toml file
```
[development]
    [development.sentry]
    dsn = ''

    [development.postgresql]
    host = 'localhost'
    port = '5432'
    name = 'postgres'
    user = 'postgres'
    password = ''
```
How to set host throw env var. I tried `POSTGRESQL_HOST` but it did not work.

Thanks!

**Comment by rochacbruno** [comment]
BY default dynaconf reads only variables prefixed with `DYNACONF_`

so

```bash
export DYNACONF_POSTGRESQL_HOST=otehrhost.com
```

**Comment by heckad** [comment]
I added variables into `.env` file and added `DYNACONF_` to each, but it didn't work. How do I know if dynaconf find the .env file?

**Comment by rochacbruno** [comment]
@heckad 

```
export DEBUG_LEVEL_FOR_DYNACONF=DEBUG
```

You will see lots of debug messages

**Comment by rochacbruno** [comment]
In dynaconf 3.x dotenv is disabled by default and users must explicit pass path to dotenv and enable it https://www.dynaconf.com/envvars/#dot-env
