### ISSUE TITLE
Exporting settings with substituted strings question

### ISSUE THREAD

**Issue by jernejg** [rochacbruno/dynaconf#333]
Hi,

I'm using @format token in my settings file and I can't find a way how to export all the settings with strings already substituted. 

I tried:
```
dynaconf list -o path/to/file.json
``` 
and
``` 
dynaconf write json
``` 
but they both export the un-substituted values (values still include {} substitution placeholders).

Is there a way to export a "rendered" settings file?

Thanks for any hints

**Comment by jernejg** [comment]
To give some background what I would like to achieve. 

I want to expose the settings to my Jenkins pipeline script. Trigger export from the Groovy build script (via dynaconf CLI) and consume the json.

**Comment by rochacbruno** [comment]
@jernejg this is not supported yet on the CLI we can add an option for that like `dynaconf list -o ... --evaluate-lazy-types`

But for now you can achieve that using this workaround:

```py
import json
from dynaconf import settings
# the access thought [k] is firing the evaluation of format template
data = {k: settings[k] for k in settings.as_dict()}
json.dump(data, open("path/to/file.json", "w"))
```

I will leave this issue opened so we can add it as a new option to the CLI `--evaluate-lazy`

**Comment by jernejg** [comment]
@rochacbruno great, thank you for the workaround!

**Comment by rochacbruno** [comment]
Now all the values are evaluated on access so this should be working.

What we miss is a way to export raw values from that settings
