### ISSUE TITLE
[RFC] Be able to load configs when being imported from a zip package

### ISSUE THREAD

**Issue by kylegao91** [rochacbruno/dynaconf#336]
**Is your feature request related to a problem? Please describe.**
I'm using Dynaconf in an Airflow dag which is then packaged in a zipped file as described [here](https://airflow.apache.org/docs/stable/concepts.html#packaged-dags).  The zipped file will be loaded by Airflow using `importlib.import_module`.  The fact that it is a zip file breaks how Dynaconf navigate the folder structure so that my code is not able to find the correct place for settings.  The structure looks like this:

```
dag.zip
- config
- source
  - code.py # from dynaconf import settings
```

**Describe the solution you'd like**
Be able to load the settings as if the zip folder is a normal directory.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by rochacbruno** [comment]
Right now the only solution I see is having your settings as a python file `config.py` and then passing to dynaconf explicitly

```
settings = Dynaconf(settings_file="path.importable.by.python")
```

**Comment by WenbinHou** [comment]
+1 for this feature
