### ISSUE TITLE
'box_it_up' key in dict

### ISSUE THREAD

**Issue by And2Devel** [rochacbruno/dynaconf#341]
**Describe the bug**
Loading dictionary from yaml type config, adds additional pair: 'box_it_up': True

**To Reproduce**
1. create the following settings.yaml:
development:
  WEEK_DAYS:
    FRI: false
    MON: false
    SAT: false
    SUN: false
    THU: false
    TUE: false
    WED: false

2. Read using all_days = settings.WEEK_DAYS

3. Result is as follows:
all_days = {'FRI': False, 'MON': True, 'SAT': False, 'SUN': False, 'THU': False, 'TUE': False, 'WED': False, 'box_it_up': True}

**Environment (please complete the following information):**
 - OS: Windows 10
 - Python 3.8.2
 - Dynaconf Version 2.2.3

**Comment by rochacbruno** [comment]
It is fixed in https://github.com/rochacbruno/dynaconf/commit/3711d7e0643a829ac5acbc9c7db885f44af16840 pending release. 

available if installed with `pip install dynaconf --pre` to get the pre release 3.0.0rc1

**Comment by rochacbruno** [comment]
Resolved in new versions
![Screenshot_2020-07-27_16-45-17](https://user-images.githubusercontent.com/458654/88584772-8f51e680-d028-11ea-9c9c-7fcf2259471f.png)
