### ISSUE TITLE
File substitution

### ISSUE THREAD

**Issue by jernejg** [rochacbruno/dynaconf#343]
Hi,

I am wondering what would be the best way to substitute placeholders in a file using values from dynaconf settings file.

Lets say we have a simple **employee.yaml** file:

```
-  martin:
    name: Martin D'vloper
    job: {settings.JOB}
```

How could I get the placeholder {settings.JOB} replaced with the actual value?

I am quite new to Python, but at the moment I'm thinking if this is something that could be solved by passing the contents of the yaml file and the settings object to  Python's **eval()** function ? Or is there some less extreme solution? Thanks!

**Comment by tarunwadhwa13** [comment]
Not an expert but I don't think this is something which Dynaconf should even do. Variable interpolation is something which Yaml loader should handle. 
A workaround could be set tags in YAML and add constructors to replace tag with values

You can check the implementation here - https://stackoverflow.com/a/53043084

You can convert Dynaconf settings object to dict using settings.as_dict()

**Comment by rochacbruno** [comment]
This is a use case for `@format`

```
-  martin:
    name: Martin D'vloper
    job: "@format {this.JOB}"
```

**Comment by rochacbruno** [comment]
Docs here: https://www.dynaconf.com/dynamic/
