### ISSUE TITLE
[RFC] Consul Support in Dynaconf

### ISSUE THREAD

**Issue by tarunwadhwa13** [rochacbruno/dynaconf#351]
**Is your feature request related to a problem? Please describe.**
We use Hashicorp consul for config management. We also have some startup configs stored in a file. Dynaconf works very well in managing local config but we have to implement another handler for consul config management

**Describe the solution you'd like**
A cohesive solution, an integration with consul too for fetching configs on the fly and watching for changes. Considering the popularity of consul, it will be quite useful for other folks too :)

**Describe alternatives you've considered**
We have a consul handler implementation but that requires managing multiple config managers in one project

**Comment by tarunwadhwa13** [comment]
In case anyone needs it, we added a custom loader to load configs from Consul. A Simple ConsulReader was made using python-consul package. Keys were fetched and loaded in obj


```
# Consul loader for Dynaconf
from .consul_handler import ConsulClient

def load(obj, env=None, silent=True, key=None, filename=None):
    """
    Reads and loads in to "obj" a single key or all keys from source
    :param obj: the settings instance
    :param env: settings current env (upper case) default='DEVELOPMENT'
    :param silent: if errors should raise
    :param key: if defined load a single key, else load all from `env`
    :param filename: Custom filename to load (useful for tests)
    :return: None
    """
    # Load data from your custom data source (file, database, memory etc)
    # use `obj.set(key, value)` or `obj.update(dict)` to load data
    # use `obj.logger.debug` to log your loader activities
    # use `obj.find_file('filename.ext')` to find the file in search tree
    # Return nothing

    consul_client = ConsulClient(
        host=obj.CONSUL.HOST,
        token=obj.CONSUL.TOKEN,
        root_path=obj.CONSUL.ROOT_PATH
    )
    fetch_keys = obj.CONSUL.pathlist
    data = consul_client.get_finalized_value(keys=fetch_keys, format="yaml")
    obj.update(data, loader_identifier='consulremote')
```

**Comment by rochacbruno** [comment]
I will personally not implement or support an  embedded consul loader, I think this is better to be added as a new example/ and documentation explaining how to create new loaders and then is up to the user to add it.

It can also be offered as  a plugin.
