### ISSUE TITLE
Custom Loader is slow due to debug message[bug]

### ISSUE THREAD

**Issue by jcavalheiro** [rochacbruno/dynaconf#352]
**Describe the bug**
Loading of files using a custom loader is particularly slow because of a debug message that forces the file contents to be concatenated into a string

**To Reproduce**
Create a custom loader and use the existing BaseLoader (from dynaconf.loaders.base import BaseLoader) class to load the file

3. Having the following app code:

<details>
<summary> Code </summary>

```python
    for file in candidate_file_names:
        found_file = obj.find_file(file)

        if found_file:
            break
    else:
        return

    loader = BaseLoader(
        obj=obj,
        env=env,
        identifier="json",
        extensions=JSON_EXTENSIONS,
        file_reader=json_reader,
        string_reader=json_reader,
    )

    loader.load(filename=found_file, key=key, silent=True)
...
```

</details>

**Expected behavior**
The execution time should be much lower, in some cases (e.g. 20mb files) it takes more than twice the expected time

**Additional context**
The log message is the following:

<details>
<summary> Code </summary>
dynaconf/loaders/base.py (BaseLoader class, lines 154 to 161)

```python
self.obj.logger.debug(
    "{}_loader: {}[{}]{}".format(
        self.identifier,
        os.path.split(source_file)[-1],
        env,
        list(data.keys()) if is_secret else data,
    )
)
...
```
</details>

**Comment by rochacbruno** [comment]
Fixed in master #362
