### ISSUE TITLE
Bug with namespace with YAML

### ISSUE THREAD

**Issue by Sytten** [rochacbruno/dynaconf#36]
Hey!

I tracked a bug in the namespace with YAML.
The problem is basically that the environment variable DYNACONF_NAMESPACE is loaded in the `execute_loaders(self, namespace=None, silent=None, key=None)` AFTER the YAML as been already parsed in `module_loader(obj, settings_module=None, namespace=None, silent=False)`.
And for some reason the YAML loader isn't rexecuted in the `execute_loaders`, not sure why.

Thanks ;)

**Comment by rochacbruno** [comment]
Thanks for reporting, I'll take a look soon

**Comment by Sytten** [comment]
I would have done the fix myself, but I'm not sure how you want to handle it. We could add it the setup or init very easily, but I'm not sure it's the proper way to handle configurations. 
I believe it also affects the python parser.

**Comment by rochacbruno** [comment]
Fixed in https://github.com/rochacbruno/dynaconf/pull/38
