### ISSUE TITLE
[bug] User warning for the missing ".local" file

### ISSUE THREAD

**Issue by paraschakis** [rochacbruno/dynaconf#365]
**Describe the bug**
In Dynaconf v.3.0.0rc2, a user warning is issued about the missing ".local" file, even if the settings file pointed at by the option `settings_file=...` is successfully loaded. As a result, if a user wants to load a config file named "settings", s/he is forced to create a "settings.local" file (could be empty) to get rid of the annoying warning. The `silent_errors` option doesn't have any effect on this one.

**To Reproduce**
Create a settings file without the accompanying ".local" file, and try to read a key from it by calling a `get(key)` method of the Dynaconf settings object.

**Expected behavior**
When the specified settings file is loaded, there is no need to issue a warning about the missing ".local" file.
Alternatively, provide a way to suppress such warnings.

**Environment:**
 - OS: Linux/Ubuntu 18.04
 - Dynaconf Version: 3.0.0 rc2

**Comment by rochacbruno** [comment]
Fixed on 3.0.0 release thanks
