### ISSUE TITLE
The param "environments" of Dynaconf for what?

### ISSUE THREAD

**Issue by Graywd** [rochacbruno/dynaconf#367]
hi, I get a different result when I try to change param "environments".

**settings.toml**
```
[default]
POI_SERVICE_URL = "http://poi-service"
[testing]
```
```
from dynaconf import Dynaconf

settings = Dynaconf(
    envvar_prefix="DYNACONF",
    settings_files=['settings.toml', '.secrets.toml'],
    environments=True,
)


# `envvar_prefix` = export envvars with `export DYNACONF_FOO=bar`.
# `settings_files` = Load this files in the order.

settings2 = Dynaconf(
    envvar_prefix="DYNACONF",
    settings_files=['settings.toml', '.secrets.toml'],
)

print(getattr(settings, "POI_SERVICE_URL", None) is None) # False
print(getattr(settings2, "POI_SERVICE_URL", None) is None) # True
```

**Comment by rochacbruno** [comment]
envless settings is like

```toml
POI_SERVICE_URL = "http://poi-service"
```

then settings should be 
```py
settings2 = Dynaconf(
    envvar_prefix="DYNACONF",
    settings_files=['settings.toml', '.secrets.toml'],
)
```

When you need environments
```toml
[default]
POI_SERVICE_URL = "http://poi-service"
```

```py
settings = Dynaconf(
    envvar_prefix="DYNACONF",
    settings_files=['settings.toml', '.secrets.toml'],
    environments=True,
)
```

The environments will enable the split of settings data by layered environments.

https://dynaconf.com/configuration/#environments

**Comment by Graywd** [comment]
@rochacbruno Thank you very much. 
I have tried to figure it out by searching the whole Dynaconf source code but find nothing about this param. Could you point the place where do its part out?

**Comment by rochacbruno** [comment]
@Graywd it is defined as a default setting `ENVIRONMENTS_FOR_DYNACONF` here https://github.com/rochacbruno/dynaconf/blob/master/dynaconf/default_settings.py#L90 which is aliased to `environments` here: https://github.com/rochacbruno/dynaconf/blob/master/dynaconf/base.py#L103
