### ISSUE TITLE
[RFC]  Support computed values.

### ISSUE THREAD

**Issue by rochacbruno** [rochacbruno/dynaconf#377]
For https://github.com/SatelliteQE/robottelo/pull/7774/

It is needed to allow some values to be computed at runtime, dynaconf already support lazy values using `@jinja` and `@format` but in this case it will be able to use any callable

Some fields can be computed at runtime and we can provide different API style to define it.

Options listed in comment bellow:

**Comment by rochacbruno** [comment]
It is needed to have something like:

```py
from dynaconf import Dynaconf

settings = Dynaconf(
     computed={
        "name": callable_name
     }
)
```

**Comment by rochacbruno** [comment]
Option 2: A class 

```py

class MyClass:
    def this_is_loaded_at_runtime(self):
        # can access self.settings

settings = Dynaconf(computed=MyClass)

```

**Comment by rochacbruno** [comment]
Option 3: Stick with tokens just like `@jinja` and `@format`

```py
settings = Dynaconf(
     ...
     lazy_key="@lazy module.callable args k=args"
)
```

**Comment by rochacbruno** [comment]
Option 4: USe validators to provide default and computation

```py
settings = Dynaconf(
    ...,
    validators=[
        Validator("KEY", lazy=callable, default="foo")
    ]
)

```

**Comment by rochacbruno** [comment]
Option 5: A complete Schema support #331 

```py

class MySchema(pydantic.BaseModel):
    foo = dynaconf.Lazy(**options)

    def load_foo(self):  
        # do the things


settings = Dynaconf(schema=MySchema)

```






```

**Comment by JacobCallahan** [comment]
I think option 1 is cleaner and clearer. It also wouldn't require defining a new class for each key requiring a callable.
Option 4 is a good alternative.

**Comment by rochacbruno** [comment]
@JacobCallahan PR #386 sent, after some testing this will unblock the writing of validators and computed properties.
