### ISSUE TITLE
django explicit mode: settings behavior change in dynaconf >=3.0 ?

### ISSUE THREAD

**Issue by dmsimard** [rochacbruno/dynaconf#380]
This isn't necessarily a bug in dynaconf but ara uses dynaconf for it's django [settings.py](https://github.com/ansible-community/ara/blob/master/ara/server/settings.py) and it no longer works when using dynaconf >=3.0 :(
This is tracked in ara with issue https://github.com/ansible-community/ara/issues/149

I need help understanding the issue and finding a solution which would support both <3.0 and >=3.0. I hope that you can point me in the right direction !

I believe the use case revolves around the [Django explicit mode](https://www.dynaconf.com/django/#explicit-mode).
I've read about ``settings.populate_obj(sys.modules[__name__], ignore=locals())`` which our settings.py doesn't currently use but adding it doesn't seem to make a difference. I would had liked to rely on an example but unfortunately the two django examples aren't using the "explicit" mode (see [here](https://github.com/rochacbruno/dynaconf/blob/master/example/django_example/foo/settings.py) and [here](https://github.com/rochacbruno/dynaconf/blob/master/example/django_example_compat/foo/settings.py))

The intent is to expose a minimum amount of settings (not ALL of django's settings) to a ``settings.yaml`` file that is written out to a default settings file if it doesn't exist. In other words, the settings from the file should be loaded first and be overridden by environment variables if declared. I realize that there might be some chicken and egg going on and I'm most definitely open to feedback on how to best do this if we're doing it wrong.

**To Reproduce**

What is likely the easiest example of something that worked before 3.0 is the retrieval of the ``SECRET_KEY`` that had been implemented:
```python
import os
from django.utils.crypto import get_random_string
from dynaconf import LazySettings

BASE_DIR = os.environ.get("ARA_BASE_DIR", os.path.expanduser("~/.ara/server"))
SETTINGS_FILE = os.environ.get("ARA_SETTINGS", os.path.join(BASE_DIR, "settings.yaml"))

settings = LazySettings(
    GLOBAL_ENV_FOR_DYNACONF="ARA", ENVVAR_FOR_DYNACONF="ARA_SETTINGS", SETTINGS_MODULE_FOR_DYNACONF=SETTINGS_FILE
)
[...]
def get_secret_key():
    if not settings.get("SECRET_KEY"):
        print("[ara] No setting found for SECRET_KEY. Generating a random key...")
        return get_random_string(length=50)
    return settings.get("SECRET_KEY")

SECRET_KEY = get_secret_key()
[...]
# SECRET_KEY gets written to ~/.ara/server/settings.yaml if the file doesn't already exist.
```

The above should read like: if there is a SECRET_KEY in settings.yaml, use that. Otherwise, generate a new one which later gets written to file -- which means the next time the server is loaded, the SECRET_KEY should not be generated and instead loaded from the file.

This felt like it worked before Dynaconf 3.0 and I'm kind of stumped now. Any ideas ?

**Comment by rochacbruno** [comment]
Hi @dmsimard 

The breaking changes are listed here: https://www.dynaconf.com/release_notes/#breaking-changes

For your case:

- Dynaconf now is envless by default unless you pass environments=True
- Dynaconf does not load .env files unless explicitly passed
- Dynaconf does not try to find files for you unless you specify the names or paths

To make an instance of dynaconf to work exactly as before you need

```py
from dynaconf import LazySettings

settings = LazySettings(
    environments=True,
    load_dotenv=True,
    settings_files=["settings.yaml", ".secrets.yaml"]
)


```

**Comment by dmsimard** [comment]
Hey @rochacbruno,

I tried to use ``environments=True`` and it works now.

Thanks for the help, much appreciated !
