### ISSUE TITLE
[RFC] support place-holders in configuration files

### ISSUE THREAD

**Issue by tony-kerz** [rochacbruno/dynaconf#381]
**Is your feature request related to a problem? Please describe.**

various config libraries provide various ways to integrate environment variables:

- the [node-config](https://github.com/lorenwest/node-config/wiki/Environment-Variables#custom-environment-variables) library allows a special file (e.g. `custom-environment-variables.js`) for overriding config values from specified environment variables

```js
module.exports = {
  foo: {
    bar: {
      baz: 'THIS_ENV_VAR'
    }
  }
}
```

- spring-boot allows [placeholders](https://docs.spring.io/spring-boot/docs/2.3.2.RELEASE/reference/html/spring-boot-features.html#boot-features-external-config-placeholders-in-properties) in config files that trigger replacement with either other config values or environment variables

```yaml
foo:
  bar:
    baz: ${THIS_ENV_VAR}
```

**Describe the solution you'd like**

current support in `dynaconf` for referencing environment variables looks like it requires, special naming for environment variables which could possibly be considered a [leaky-abstraction](https://www.joelonsoftware.com/2002/11/11/the-law-of-leaky-abstractions/).

for instance, the above would require an environment variable named `DYNACONF_FOO__BAR__BAZ`, where it might be a reasonable enhancement to allow something like the spring-boot strategy illustrated above which allows a placeholder syntax directly in the config files allowing arbitrary environment variable names.

other potentially interesting features of the spring-boot solution include:

- referencing other config values

```yaml
foo:
  bar:
    baz: '123'
bim:
  bam:
    boom: ${foo.bar.baz}
```

- localized defaults

```yaml
foo:
  bar:
    baz: ${OPTIONAL_ENV_VAR:some-default-value}
```

**Describe alternatives you've considered**

the existing env-var support obviously works, but the naming strategy is tightly coupled to the config solution

```
export DYNACONF_FOO__BAR__BAZ=123
```

and i thought it might be a cool feature to allow for this to be decoupled

**Additional context**

i'm a dynaconf noob, and of all the config solutions i've come across ([configparser](https://docs.python.org/3/library/configparser.html), [pyyaml](https://pyyaml.org/), [confuse](https://github.com/beetbox/confuse)), it seems to be the most flexible and functional, but i'm sure i'm not completely up to speed on all it's capabilities...

**Comment by tony-kerz** [comment]
so i think [this feature](https://www.dynaconf.com/dynamic/) is what i was looking for, nicely done!

i have a couple of related questions if anyone can provide insight:

so, i'm using yaml like so:

__.env__
```
FOO_BAR_BAZ = foo-bar-baz
FOO_BAR_BIM = foo-bar-bim
```

__settings.yaml__
```yaml
foo:
  bar:
    baz: "@format {env[FOO_BAR_BAZ]}"
    bim: "@jinja {{env.FOO_BAR_BIM}}"
dynamic_format: "@format {env[FOO_BAR_BAZ]}"
dynamic_jinja: "@jinja {{env.FOO_BAR_BIM}}"
```

__test.py__
```python
log.info(f"settings.get(foo.bar.baz)={settings.get('foo.bar.baz')}")
log.info(f"settings.get(foo.bar.bim)={settings.get('foo.bar.bim')}")
log.info(f"settings[foo.bar.baz]={settings['foo.bar.baz']}")
log.info(f"settings[foo.bar.bim]={settings['foo.bar.bim']}")
log.info(f"settings.foo.bar.baz={settings.foo.bar.baz}")
log.info(f"settings.foo.bar.bim={settings.foo.bar.bim}")
log.info(f"settings.dynamic_format={settings.dynamic_format}")
log.info(f"settings.dynamic_jinja={settings.dynamic_jinja}")
```

__output__
```
2020-08-04 23:26:24,554 - src.app - INFO - settings.get(foo.bar.baz)=foo-bar-baz
2020-08-04 23:26:24,556 - src.app - INFO - settings.get(foo.bar.bim)=foo-bar-bim
2020-08-04 23:26:24,557 - src.app - INFO - settings[foo.bar.baz]=foo-bar-baz
2020-08-04 23:26:24,558 - src.app - INFO - settings[foo.bar.bim]=foo-bar-bim
2020-08-04 23:26:24,558 - src.app - INFO - settings.foo.bar.baz={env[FOO_BAR_BAZ]}
2020-08-04 23:26:24,558 - src.app - INFO - settings.foo.bar.bim={{env.FOO_BAR_BIM}}
2020-08-04 23:26:24,558 - src.app - INFO - settings.dynamic_format=foo-bar-baz
2020-08-04 23:26:24,558 - src.app - INFO - settings.dynamic_jinja=foo-bar-bim
```

1. so, you can see that _dotted_ notation doesn't work _when nesting_, but it does work when using at the top level, is this by design, or is this a bug with yaml handling?

2. on another related, yet tangential, note, the following:

    ```
    log.info(f"json.dumps()={json.dumps(settings.as_dict())}")
    ```

   yields:

   ```
   TypeError: Object of type Lazy is not JSON serializable
   ```

   is there any built-in or suggested strategy to pre-process the `settings` object such that it replaces the lazy elements with their evaluated values?

**Comment by rochacbruno** [comment]
This is fixed by #375 (this issue is duplicate of #359)

You can test it by installing Dyanconf from github master or wait next release

**Comment by tony-kerz** [comment]
sweet @rochacbruno this thing rocks! 

i know slightly off-topic, but do you have any suggestions on a strategy for serializing a settings object containing these dynamic-variables (the "lazy is not serializable" thing).

some kind of strategy to convert the "lazy" variables to "eager/evaluated"...?

**Comment by rochacbruno** [comment]
@tony-kerz this issue has been also solved! now when you call `.as_dict` you get all the values already evaluated. The only way to get raw values is acessing `settings.VARIABLE._box_config` which stores the raw values.

**Comment by tony-kerz** [comment]
oh-my-god, it just keeps getting better 😄 
thanks @rochacbruno !
