### ISSUE TITLE
[bug] Custom loaders documentation page is broken

### ISSUE THREAD

**Issue by cutwater** [rochacbruno/dynaconf#388]
**Describe the bug**
Custom loaders documentation page is not displayed correctly. This page is referenced on the main docs page in the [Dependencies](https://www.dynaconf.com/#dependencies ) section as:

> Read more on external loaders

<img width="1281" alt="Screenshot_20200810_183847" src="https://user-images.githubusercontent.com/62445/89807325-c223d080-db38-11ea-955a-34899bed6f86.png">

**To Reproduce**

Open https://www.dynaconf.com/loaders/ in your browser.

**Additional context**
Lots of 404 responses in the browser network log:

<img width="1275" alt="Screenshot_20200810_184002" src="https://user-images.githubusercontent.com/62445/89807440-e8e20700-db38-11ea-9857-fcc7e0d789ff.png">
problem here.

**Comment by rochacbruno** [comment]
Thanks for reporting, this link is from old docs then I need to update reference pointing to https://www.dynaconf.com/advanced/#creating-new-loaders
