### ISSUE TITLE
[bug] LazyFormatted values don't get evaluated properly when they are not strings

### ISSUE THREAD

**Issue by cBournhonesque** [rochacbruno/dynaconf#392]
**Describe the bug**
Values using @format don't get evaluated properly in data structures that are not strings.
Instead the returned value is `<dynaconf.utils.parse_conf.LazyFormat object at 0x105737a90>`.

**To Reproduce**

1. Having the following config files:

In `settings.toml`:

```
[default]
VAL = "val"
TEST = ["a", "@format {this.VAL}]
```

2. Having the following app code:

**/path/src/app.py**
```python
from dynaconf import settings
print(settings.TEST)
...
```

</details>

**Expected behavior**
The result should be `["a", "val"]`.
Instead the second value doesn't get lazily evaluated and I get: `["a", <dynaconf.utils.parse_conf.LazyFormat object at 0x105737a90>]`

To get the value of the second element, I would have to do `print(settings.TEST[1](settings))`

**Environment (please complete the following information):**
 - OS: MacOS

**Comment by rochacbruno** [comment]
fixed on #405
