### ISSUE TITLE
[bug] fresh_vars does not work

### ISSUE THREAD

**Issue by Auxxxxlx** [rochacbruno/dynaconf#395]
**Describe the bug**

**To Reproduce**

1. Having the following folder structure

<details>
<summary> Project structure </summary>

```bash

# /path/
# ...../folder/...
# please provide your folder structure here

```
</details>

2. Having the following config files:

<details>
<summary> Config files </summary>

**/path/.env**
```bash
Your .env content here
```

and

**/path/settings.toml**
```toml
[default]
```

</details>

3. Having the following app code:

<details>
<summary> Code </summary>

**/path/src/app.py**
```python
from dynaconf import settings
...
```

</details>

4. Executing under the following environment

<details>
<summary> Execution </summary>

```bash
# other commands and details?
# virtualenv activation?

$ python /path/src/app.py
```

</details>

**Expected behavior**

**Environment (please complete the following information):**
 - OS: [e.g. Linux/Fedora29, Windows/x.x.x, Linux/Ubuntu16.x]
 - Dynaconf Version [e.g. 2.0.0/source]
 - Frameworks in use (Flask, Django? versions..)

**Additional context**

**Comment by rochacbruno** [comment]
Can you include more context to this issue?
