### ISSUE TITLE
[bug] Cannot get secrets from vault

### ISSUE THREAD

**Issue by clanzett** [rochacbruno/dynaconf#403]
**Describe the bug**
When trying to retrieve secrets from hashicorp vault without setting os envs the settings only contain the default dynaconf settings.

**To Reproduce**

1. Run local vault server as described in the documentation

2. Store some secrets in vault

3.Run this code:

<details>
<summary> Python Code </summary>

```python
from dynaconf import Dynaconf

config = Dynaconf(
            environment=True,
            vault_enabled=True,
            vault_url="http://localhost:8200",
            vault_token="myroot"
        )

print(config.as_dict())
```
</details>

**Expected behavior**
The config should include the stored secrets.

**Environment (please complete the following information):**
 - OS: [OSX]
 - Dynaconf Version [3.1.0]

**Comment by rochacbruno** [comment]
Just tried locally using `environments=True` and all tests for vault worked well

There  were some fixes included,

So feel free to reopen if problem remains

**Comment by clanzett** [comment]
The problem is that *without* using os environment variables it is not working. In fact this seems to be an issue with the documentation. The docs claim that in order to use vault the following code should work: 
`settings = Dynaconf(
    environment=True,
    vault_enabled=True,
    vault_url="http://localhost:8200",
    vault_token="myroot"  # recommended to keep as env var.
)`

... which it does not. 

This is how it works:
`settings = Dynaconf(
                environment=True,
                vault={'url': 'http://localhost:8200', 'token': 'myroot' },
                vault_enabled=True,
            )`

So there is a dict called "vault" which accepts the url and the token as key/value pairs.

**Comment by rochacbruno** [comment]
Fix the docs

**Comment by clanzett** [comment]
and it would be nice to have some self explaining doc_strings as well ;-) thx!!
