### ISSUE TITLE
Centos 7 - dynaconf

### ISSUE THREAD

**Issue by luizcarlospedrosogomes** [rochacbruno/dynaconf#409]
quando executo o comando: dynaconf list, não lista as variaveis, me parece que tentar executar o app

quando tento executar o app não encoontra as configurações

![image](https://user-images.githubusercontent.com/9791364/93043062-184bce00-f627-11ea-825a-90c9bf6ece28.png)

para sempre nesse erro, será que é algo que eu esqueci?

**Comment by rochacbruno** [comment]
It is a bug already fixed in the pre-release version `pip install --pre dynaconf` should get you the latest RC and probably fix this issue
