### ISSUE TITLE
[bug] Attributes not loaded when using setenv and format

### ISSUE THREAD

**Issue by sp-fm** [rochacbruno/dynaconf#434]
**Bug Description**
 I first set the environment to 'development' using the `settings.setenv()` method. Then I tried to access the 'DB_PATH' using the `@format` token in order to use the 'DB_NAME' as shown in the example codes. But, I am getting the `AttributeError: 'Settings' object has no attribute 'DB_NAME'`.

**To Reproduce**

1. Having the following folder structure

<details>
<summary> Project structure </summary>

```bash

.
│
├── configs/
│   ├── .secrets.toml
│   └── settings.toml
│
├── my_package/
│   └── my_program.py
│
└── config.py

```
</details>

2. Having the following config files:

<details>
<summary> Config files </summary>

**./configs/settings.toml**
```toml
[default]
DB_NAME = "mydb.db"

[development]
DB_PATH = "@format {env[HOME]}/{this.current_env}/{this.DB_NAME}"
```

</details>

3. Having the following app code:

<details>
<summary> Code </summary>

**./my_package/my_program.py**
```python
import click

from config import settings


@click.group()
@click.option("--config", default="default")
def main(config):
    click.echo(f"Environment: {config}")
    settings.setenv(config)
    return


@main.command()
def dynaconf():
    click.echo(f"Database Path: {settings.DB_PATH}")
    return


if __name__ == "__main__":
    main()
```

**./config.py**
```python
from dynaconf import Dynaconf

settings = Dynaconf(
    envvar_prefix="DYNACONF",
    settings_files=["configs/settings.toml", "configs/.secrets.toml"],
    environments=True,
)
```

</details>

4. Executing under the following environment

<details>
<summary> Execution </summary>

```bash
# virtualenv: poetry

$ python -m my_package.my_program --config development dynaconf
```

</details>

**Expected behavior**
Expected DB_PATH to be set to `$HOME/development/mydb.db`.

**Environment:**
 - OS: Linux/Ubuntu 18.04.5 LTS
 - Dynaconf Version: 3.1.1

**Additional context**
I can access DB_PATH just fine if I don't use the 'setenv' method or make use of the `@jinja` token.

**Comment by rochacbruno** [comment]
@sp-fm bug is fixed and will be part of next release. Thanks.
