### ISSUE TITLE
Error: --django option requires an argument[bug]

### ISSUE THREAD

**Issue by AlekseiKhatkevich** [rochacbruno/dynaconf#451]
Running  `dynaconf init -f yaml --django` from Django's project root generates following error:

```
(entropy) C:\Users\hardcase1\PycharmProjects\entropy>dynaconf init -f yaml --django
Error: --django option requires an argument

```
DJANGO_SETTINGS_MODULE  is set

```
import django_manage_shell;
django_manage_shell.run("C:/Users/hardcase1/PycharmProjects/entropy")
PyDev console: starting.
Python 3.9.0 | packaged by conda-forge | (default, Oct 10 2020, 20:35:00) [MSC v.1916 64 bit (AMD64)] on win32
Django 3.1.2
import os 
os.getenv('DJANGO_SETTINGS_MODULE')
'entropy.settings'

```

manage.py locates in project's root:

К```
аталог: C:\Users\hardcase1\PycharmProjects\entropy

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       17.10.2020     12:20                .idea
d-----       17.10.2020     12:22                entropy
d-----       16.10.2020     20:46                staticfiles
d-----       14.10.2020     19:28                templates
d-----       17.10.2020     11:53                uvicorn
d-----       17.10.2020     12:18                __pycache__
-a----       16.10.2020     18:00           2398 .gitignore
-a----       16.10.2020     17:53           1310 environment.yml
-a----       16.10.2020     20:45            283 manage.py
-a----       16.10.2020     17:54             38 notes.txt
-a----       17.10.2020     12:09            192 packages
-a----       16.10.2020     17:32            138 Pipfile
-a----       16.10.2020     17:32            453 Pipfile.lock
-a----       17.10.2020     11:55            940 todo.txt

PS C:\Users\hardcase1\PycharmProjects\entropy>

```

**Comment by Real-Gecko** [comment]
How did you get around #465? I had to manually edit `dynaconf` source inside `venv` to solve it and then your issue is solved like this:
```
dynaconf init -f yaml --django .
```
Note the *.* (dot) symbol in the end, looks like we now have to specify folder where init will put all needed files.
