### ISSUE TITLE
use callable in settings.yaml

### ISSUE THREAD

**Issue by AlekseiKhatkevich** [rochacbruno/dynaconf#452]
I would like to ask if it possible to use python callable in settings.yaml somehow?

Usecase:

development:
    INTERNAL_IPS:
        - '127.0.0.1'
        - 'localhost'
        - '0.0.0.0'
production:
     # INTERNAL_IPS need to be calculated...
    ```
    hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
    INTERNAL_IPS = [ip[:-1] + "1" for ip in ips]
    ```
It is almost possible to do it with jinja, but jinja operates only on strings. In this case it is a list.

**Comment by rochacbruno** [comment]
You can provide a computed value to dynaconf as  a validator. Currently there is no way to have it in a static config file.

https://www.dynaconf.com/validation/#computed-values

**Comment by rochacbruno** [comment]
having a callable as part of a static config file is not safe, so right it can be done with computed values on validators.
