### ISSUE TITLE
Allow core_loaders to be case insensitive.

### ISSUE THREAD

**Issue by trallnag** [rochacbruno/dynaconf#455]
**Describe the bug**

When using the `core_loaders` attribute with the value `["yaml"]` Dynaconf fails reading settings from the respective YML configuration file.

**To Reproduce**

1. Go into an empty dir.

2. Setup environment.

  * Python 3.9
  * `pip install dynaconf[yaml]` or `poetry add "dynaconf[yaml]"`
  * dynaconf 3.1.2
  * ruaml.yml 0.16.2

3. Create `settings.yml`

```yml
test: hallo
logging:
  json: true
```
4. Create `test.py` and execute it. It will succeed.

```python
from dynaconf import Dynaconf

settings = Dynaconf(
    merge_enabled=True,
    settings_files=["settings.yml"],
)

print(settings.TEST)
print(settings.LOGGING.JSON)
```

5. Add attribute `core_loaders` as recommended in the Dynaconf doc. Execute. This will fail.

```python
from dynaconf import Dynaconf

settings = Dynaconf(
    merge_enabled=True,
    core_loaders=["yaml"],
    settings_files=["settings.yml"],
)

print(settings.TEST)
print(settings.LOGGING.JSON)
```

**Comment by trallnag** [comment]
Nevermind, it has to be uppercase.

**Comment by rochacbruno** [comment]
Lets work on improving it and have make it to accept lower case.
