### ISSUE TITLE
Regression detected [was] Case insensitive access of structures inside lists

### ISSUE THREAD

**Issue by trallnag** [rochacbruno/dynaconf#462]
**Describe the bug**

When I access a Box that is stored in a BoxList the access becomes case sensitive. I know about DynaBox, but for some reason  the list access returns a vanilla Box and not a DynaBox.

Background: I need to parse more or less complex data from the config (routing stuff) and enrich the data structures with defaults after parsing. Therefore I want to set change the settings from within code.

If something like this is out of scope for Dynaconf, could someone recommend an alternative approach? Maybe only store user provided routing settings and all the other general simple configs like logging level in Dynaconf and manage the routing config elsewhere?

**To Reproduce**

1. Run the following code placed in `tmp.py` with pytest `pytest tmp.py`:

```python
from dynaconf.vendor.box import BoxList, Box
from dynaconf.utils.boxing import DynaBox

def test_accessing_dynabox_inside_boxlist_inside_dynabox():
    data = DynaBox({"nested": [{"deeper": "nest"}]})
    assert data.nested[0].deeper == "nest"
    assert data.NESTED[0].deeper == "nest"
    with pytest.raises(BoxKeyError):
        assert data.NESTED[0].DEEPER == "nest"

    data = DynaBox({"nested": [DynaBox({"deeper": "nest"})]})
    assert data.nested[0].deeper == "nest"
    assert data.NESTED[0].deeper == "nest"
    with pytest.raises(BoxKeyError):
        assert data.NESTED[0].DEEPER == "nest"
```

Even though I am passing in a DynaBox it gets changed to a Box

Dynaconf 3.1.2

**Comment by trallnag** [comment]
Here is a shorter self-contained test.

```python
def test_accessing_dynabox_inside_boxlist_inside_dynabox():
    data = DynaBox({"nested": [{"deeper": "nest"}]})
    assert data.nested[0].deeper == "nest"
    assert data.NESTED[0].deeper == "nest"
    with pytest.raises(BoxKeyError):
        assert data.NESTED[0].DEEPER == "nest"

    data = DynaBox({"nested": [DynaBox({"deeper": "nest"})]})
    assert data.nested[0].deeper == "nest"
    assert data.NESTED[0].deeper == "nest"
    with pytest.raises(BoxKeyError):
        assert data.NESTED[0].DEEPER == "nest"
```

**Comment by trallnag** [comment]
Make this is not a bug but a feature request? I don't really know how python-box works, but maybe what is necessary is a DynaList that turns given `dict` or `Box` instances into DynaBox objects instead

**Comment by rochacbruno** [comment]
Probably the change must go in https://github.com/rochacbruno/dynaconf/blob/master/dynaconf/vendor_src/box/box_list.py#L24
 which receives a box_class argument, we need to provide Dynabox.

Then we run https://github.com/rochacbruno/dynaconf/blob/master/minify.sh to get the update applied into vendored packages.

Another option (less intrusive) would be doing something like this https://github.com/rochacbruno/dynaconf/blob/56130a8b09779f13ae1d843e3e326739f63c5bec/dynaconf/base.py#L840 but as this is a list it would need to be recursive, so this is also a place to try it https://github.com/rochacbruno/dynaconf/blob/56130a8b09779f13ae1d843e3e326739f63c5bec/dynaconf/utils/__init__.py#L359-L366

**Comment by trallnag** [comment]
@rochacbruno, I gave the second option a try and it does not work due to a circular dependency.

`__init__.py`:

```python
from dynaconf.utils.boxing import DynaBox
```

`boxing.py`:

```python
from dynaconf.utils import recursively_evaluate_lazy_format
```

**Comment by dmsimard** [comment]
o/ @rochacbruno 

Getting reports of users being broken with dynaconf 3.1.3 (told them to pin to 3.1.2 in https://github.com/ansible-community/ara/issues/212 while I figure this out) and this seems to be related.

We use LazySettings for django's [settings.py](https://github.com/ansible-community/ara/blob/master/ara/server/settings.py) and to_list is suddenly returning an exception:
```
Traceback (most recent call last):
  File "/home/build/ara/bin/ara-manage", line 8, in <module>
    sys.exit(main())
  File "/home/build/ara/lib/python3.6/site-packages/ara/server/__main__.py", line 41, in main
    if not os.path.exists(settings.ARA_SETTINGS):
  File "/home/build/ara/lib/python3.6/site-packages/django/conf/__init__.py", line 79, in __getattr__
    self._setup(name)
  File "/home/build/ara/lib/python3.6/site-packages/django/conf/__init__.py", line 66, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/build/ara/lib/python3.6/site-packages/django/conf/__init__.py", line 157, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/build/ara/lib/python3.6/site-packages/ara/server/settings.py", line 263, in <module>
    ALLOWED_HOSTS=ALLOWED_HOSTS.to_list(),
AttributeError: 'list' object has no attribute 'to_list'
```

You had suggested to use ``to_list`` a while back in issue https://github.com/rochacbruno/dynaconf/issues/257

Does it ring you a bell ?

Thanks !

**Comment by rochacbruno** [comment]
@dmsimard I see a problem here: 

https://github.com/ansible-community/ara/blob/master/ara/server/settings.py#L80

```py
ALLOWED_HOSTS = settings.get("ALLOWED_HOSTS", ["::1", "127.0.0.1", "localhost"])
```

When `ALLOWED_HOSTS` is defined on the settings file it will be a `BoxList` because Dynaconf loaded it.
When it is not found, then, `settings.get` (dict get) will return the default (second argument) which is a python `list` 

Anyway I am introducing a change to make every passed to as `default` to get to be converted to `BoxList` or `BoxDict` to keep the same API.

In your case, might be other problem, the settings file was not loaded for some reason? and then default value used for the first time?

We can figure it out as I will release a HOTFIX version 3.1.4 later today.

**Comment by dmsimard** [comment]
> When ALLOWED_HOSTS is defined on the settings file it will be a BoxList because Dynaconf loaded it.
When it is not found, then, settings.get (dict get) will return the default (second argument) which is a python list

That explanation makes sense to me, thanks. So, in other words, we would not have had the issue if we had written it as something like:

```python
ALLOWED_HOSTS = settings.get("ALLOWED_HOSTS", BoxList(["::1", "127.0.0.1", "localhost"]))
```

> We can figure it out as I will release a HOTFIX version 3.1.4 later today.

Appreciate the quick turnaround, thanks !

**Comment by rochacbruno** [comment]
@dmsimard `pip install https://github.com/rochacbruno/dynaconf/tarball/462.b` <-- this will make defaults to be Boxed by default. Any inputs?

Later today 3.1.4 hotfix will be released.

**Comment by dmsimard** [comment]
@rochacbruno fixes it for me but just in face FYI I had to pass ``--upgrade`` to an existing installation:

```
/tmp/ara/bin/pip install https://github.com/rochacbruno/dynaconf/tarball/462.b
Collecting https://github.com/rochacbruno/dynaconf/tarball/462.b
  Downloading https://github.com/rochacbruno/dynaconf/tarball/462.b
     | 2.7 MB 781 kB/s
Requirement already satisfied (use --upgrade to upgrade): dynaconf==3.1.3 from https://github.com/rochacbruno/dynaconf/tarball/462.b in /tmp/ara/lib/python3.9/site-packages
```

**Comment by rochacbruno** [comment]
Must be fixed in https://github.com/rochacbruno/dynaconf/releases/tag/3.1.4 please reopen if any more issue.

thanks :)
