### ISSUE TITLE
[bug] ModuleNotFoundError

### ISSUE THREAD

**Issue by Real-Gecko** [rochacbruno/dynaconf#465]
**Describe the bug**
I tried to initialize dynaconf settings for Django as described in docs:
```bash
export DJANGO_SETTINGS_MODULE=myproj.settings
dynaconf init -f yaml --django
```
And got following error:
```bash
  File "/home/realgecko/Work/energy/cabinet/app/venv/lib/python3.6/site-packages/dynaconf/cli.py", line 64, in set_settings
    import dynaconf.contrib.django_dynaconf  # noqa
ModuleNotFoundError: No module named 'dynaconf.contrib.django_dynaconf'
```
Which is not surprising as dynaconf has `dynaconf/contrib/django_dynaconf_v2.py` and no `dynaconf/contrib/django_dynaconf.py`

**To Reproduce**

```bash
mkdir dyna-test
cd dyna-test
python -m venv venv
source venv/bin/activate
pip install django dynaconf
django-admin startproject myproj .
export DJANGO_SETTINGS_MODULE=myproj.settings
dynaconf init
```
```
(venv) realgecko@archlinux ~/D/dyna-test> tree -v -I venv
.
├── manage.py
└── myproj
    ├── __init__.py
    ├── __pycache__
    │   ├── __init__.cpython-38.pyc
    │   └── settings.cpython-38.pyc
    ├── asgi.py
    ├── settings.py
    ├── urls.py
    └── wsgi.py

2 directories, 8 files
```

**Expected behavior**
As described in docs:
```bash
Django app detected
⚙️  Configuring your Dynaconf environment
------------------------------------------
🎛️  settings.yaml created to hold your settings.

🔑 .secrets.yaml created to hold your secrets.

🙈 the .secrets.yaml is also included in `.gitignore`
beware to not push your secrets to a public repo
or use dynaconf builtin support for Vault Servers.

⁉  path/to/yourproject/settings.py is found do you want to add dynaconf? [y/N]:
```

**Environment**
 - OS: Arch Linux
 - Dynaconf Version 3.1.2
 - Django 3.1.3
 - Python 3.8.6

**Comment by fronbasal** [comment]
I am still experiencing the same issue.

**Comment by Real-Gecko** [comment]
> I am still experiencing the same issue.

You need to install directly from git
```bash
pip install git+git://github.com/rochacbruno/dynaconf.git
```
Then do things [described in docs](https://www.dynaconf.com/#using-django)
![image](https://user-images.githubusercontent.com/2231969/109295218-893f1500-7858-11eb-99a8-ede79aeea4c6.png)
@rochacbruno can you please make a release?

**Comment by fronbasal** [comment]
So no difference to the `django-configurations` package in that regard :( 
I might move away from it once there is a new release, until then I will have to continue using `django-configurations`.
Thank you for the heads up, @Real-Gecko!

**Comment by Real-Gecko** [comment]
> So no difference to the `django-configurations` package in that regard :(
> I might move away from it once there is a new release, until then I will have to continue using `django-configurations`.

Version 3.1.3rc1 is released, so you can now simply use `pip install dynaconf` and `pip freeze > requirements.txt`.
Works as intended.
