### ISSUE TITLE
Load setting files

### ISSUE THREAD

**Issue by henriqueribeiro** [rochacbruno/dynaconf#467]
(sorry for this newbie and probably dumb question)

I have the following project structure
```
.
├── ...
├── project
│   ├── src
│   │   ├── app.py
│   ├── conf.py
│   ├── __init__.py
│   ├── settings.toml
│   ├── configs
│   │   ├── config1.yaml
│   │   ├── config2.yaml
```
and in essence, the question is how can I load `config1.yaml` and `config2.yaml`.

I added the path to the files in settings_files at `conf.py` but then, when I import dynaconf in `src/app.py` using ` from dynaconf import settings` I have no access to the defined settings.

Probably I misunderstood the documentation but I would really appreciate it if you can help me :)

**Comment by rochacbruno** [comment]
I added #535 PR just to ensure we dont have a bug.

`from dynaconf import settings` is not recommended anymore, 

is you created your instance on `conf.py` you must import from there `from conf import settings`
