### ISSUE TITLE
[RFC] add an option to auto-output all vars after the settings are loaded  [was] Is is possible to export all settings of a running service?

### ISSUE THREAD

**Issue by jruizaranguren** [rochacbruno/dynaconf#472]
It is a great feature that env_vars can override any setting loaded from files. 

For diagnose, debug etc. many times it is useful to be able to extract the configuration of a running service (perhaps it loaded it from database, files and env_vars). 

Do we have any means to get all `DYNACONF` settings that a running service is using?
Would it be possible to auto-export all config to env vars after loading?

**Comment by rochacbruno** [comment]
@jruizaranguren dynaconf loads settings from environment, if you have access to that environment you can export it though the command line.

If the settings are changed dynamically and you need a `freeze` so you will need some process inspection tool like https://pypi.org/project/pyrasite/

**Comment by rochacbruno** [comment]
Right now it is possible to output all the vars on a settings object, but it requires manual intervention.

The idea here is to add an explicity option like

```py

settings = Dynaconf(...)
settings.export("/path/output.json")

```

with that set, right after all the loaders are executed the settings will be saved to a JSON file.

> **NOTE**: It is not possible for a Python application to write back to the console environments variable.
