### ISSUE TITLE
[RFC] Support for Vault authentication through EC2 metadata service

### ISSUE THREAD

**Issue by SuperStevenZ** [rochacbruno/dynaconf#493]
**Is your feature request related to a problem? Please describe.**
I'm currently running an app in a EC2 instance, where I'd like to integrate dynaconf with Vault for my configurations. However, it seems dynaconf [current only supports AWS authentication through boto3 session](https://github.com/rochacbruno/dynaconf/blob/master/dynaconf/loaders/vault_loader.py), but not through [EC2 metadata service](https://hvac.readthedocs.io/en/stable/usage/auth_methods/aws.html#ec2-metadata-service) that I'm using. It will be nice if we could add support for it.

**Describe the solution you'd like**
Providing optional configurations to accept EC2 roles to authenticate through EC2 metadata service.

**Describe alternatives you've considered**
I'm currently using HVAC client directly to walk around the issue.

**Additional context**
A unrelated observation is, even for boto3 session authentication, it seems to me that we need to add `header_value` in the call to `client.auth.aws.iam_login()` as well, otherwise I'm receiving error. `hvac.exceptions.InvalidRequest: error validating X-Vault-AWS-IAM-Server-ID header: missing header "X-Vault-AWS-IAM-Server-ID", on post`

**Comment by jerosa** [comment]
Hi! I also need this authentication method and I could work on its implementation as it should not be a big change, just ask for `header_value`, `region` and `instance_role`.
