### ISSUE TITLE
AttributeError: 'Settings' object has no attribute 'TOKEN'

### ISSUE THREAD

**Issue by Krausso** [rochacbruno/dynaconf#499]
### Everything is specified in a screenshot, unless I'd answer ur questions
![зображення](https://user-images.githubusercontent.com/52201020/103479689-17a69580-4dd8-11eb-817e-7212e8d30fa8.png)

**Comment by rochacbruno** [comment]
You are missing the `environments=True` argument.

**Comment by Krausso** [comment]
Thx, that doesn't work but I made something that actually works and I dunno how:D
