### ISSUE TITLE
[bug] Attributized references in dynamic variable formatting

### ISSUE THREAD

**Issue by mshriver** [rochacbruno/dynaconf#529]
**Describe the bug**
Attributized references of the `settings` instance within dynamic variable string formatting results in AttributeError, when this should be supported.  Dictionary key references (without quotes) work correctly, and after a brief discussion with @rochacbruno it was confirmed attributized access should work as well, as documented in the dynamic variable examples.

Attributized access against the same `settings` instance that is used within the dynamic variable formatting does work, so I believe my settings instance is correctly generated. 

**To Reproduce**

1. Having the following folder structure

This was found while using dynaconf in the SatelliteQE/robottelo project:
https://github.com/SatelliteQE/robottelo

```
conf/*.yaml
robottelo/config/__init__.py
```

2. Having the following config files:

<details>
<summary> Config files </summary>

**/conf/repos.yaml**
```yaml
REPOS:
  RHEL_REPO_HOST: http://hostname.example.com
  RHEL6_REPO: '@format {this.repos.rhel_repo_host}/pub/rhel6.repo'
```
</details>

3. Having the following app code:

<details>
<summary> Code </summary>

**/robottelo/config/__init__.py**
```python
from dynaconf import LazySettings
from .validators import validators as dynaconf_validators

dynaconf_settings = LazySettings(
    envvar_prefix="ROBOTTELO",
    core_loaders=["YAML"],
    settings_file="settings.yaml",
    preload=["conf/*.yaml"],
    includes=["settings.local.yaml", ".secrets.yaml", ".secrets_*.yaml"],
    envless_mode=True,
    lowercase_read=True,
)

dynaconf_settings.validators.register(**dynaconf_validators)
dynaconf_settings.validators.validate()
```

</details>

4. Executing under the following environment

<details>
<summary> Execution </summary>

```bash
$ python -c "from robottelo.config import dynaconf_settings; print(dynaconf_settings.repos.rhel6_repo)"

<truncated traceback>
File "/home/setup/repos/robottelo/.robottelo/lib64/python3.8/site-packages/dynaconf/vendor/box/box.py", line 236, in __repr__
    def __repr__(A):return f"<Box: {A.to_dict()}>"
  File "/home/setup/repos/robottelo/.robottelo/lib64/python3.8/site-packages/dynaconf/vendor/box/box.py", line 243, in to_dict
    A=dict(D)
  File "/home/setup/repos/robottelo/.robottelo/lib64/python3.8/site-packages/dynaconf/utils/boxing.py", line 23, in evaluate
    return recursively_evaluate_lazy_format(value, settings)
  File "/home/setup/repos/robottelo/.robottelo/lib64/python3.8/site-packages/dynaconf/utils/__init__.py", line 355, in recursively_evaluate_lazy_format
    value = value(settings)
  File "/home/setup/repos/robottelo/.robottelo/lib64/python3.8/site-packages/dynaconf/utils/parse_conf.py", line 176, in __call__
    return self.formatter(self.value, **self.context)
  File "/home/setup/repos/robottelo/.robottelo/lib64/python3.8/site-packages/dynaconf/utils/parse_conf.py", line 138, in __call__
    return self.function(value, **context)
AttributeError: 'Settings' object has no attribute 'repos'
```

</details>

**Expected behavior**
The value is formatting from local references, and `http://hostname.example.com/pub/rhel6.repo` is printed.

**Environment (please complete the following information):**
 - OS: Fed 33
 - Dynaconf Version **3.1.2**

**Additional context**

Doing some debugging, I found that the AttributeError that occurs in the example reference happens only during formatting.

With the `dynaconf_settings` instance that is created `dynaconf_settings.exists('repos')` returns True.  The AttributeError is specifically during formatting.

Only within the `BaseFormatter.__call__` frame does the `AttributeError` occur.

I was able to work around this by using the following formatting string, which shows that the `AttributeError` is also only limited to the first reference under `this` contextual instance. The reference to `rhel_repo_host` doesn't raise any exception. 
```python
RHEL6_REPO: '@format {this[repos].rhel_repo_host}/pub/rhel6.repo'
```

**Comment by rochacbruno** [comment]
I guess this same issue has been fixed on https://github.com/rochacbruno/dynaconf/pull/527 I will double check if this is the same reproducer https://github.com/rochacbruno/dynaconf/blob/master/example/issues/482_layered_format/settings.toml

**Comment by mshriver** [comment]
Maybe we can set a project record for issue resolution - #527 does indeed resolve the AttributeError I described here.

**Comment by rochacbruno** [comment]
@mshriver 2 more bugs and I will do the release of 3.1.3
