### ISSUE TITLE
[breaking change] load_dotenv should default to False

### ISSUE THREAD

**Issue by rochacbruno** [rochacbruno/dynaconf#536]
For Django and Flask load_dotenv currently defaults to True

In production environments this lead to unpredictable environment, so the extensions should load it only if user explicit set to True.

**Comment by lobotmcj** [comment]
> ```python
> load_dotenv={"when": {"env": {"is_in": ["development"]}}}
> ```

@rochacbruno Are either of these supposed to work in v3.1.7? I cannot get either of them to work. the `load_dotenv={"when"...` notation is also in the `learndynaconf` repo example, but I am not finding anything like it in the documentation
