### ISSUE TITLE
Can I use layered environments for `.env`?

### ISSUE THREAD

**Issue by deknowny** [rochacbruno/dynaconf#579]
I want to set logging level in [`loguru`](https://github.com/Delgan/loguru/) due my layered environment. Can I do it?

**Comment by VaultVulp** [comment]
Hello, deknowny!

I'm personally prefer this approach:

```python
from loguru import logger

from dynaconf import Dynaconf

settings = Dynaconf(
    load_dotenv=True,
    environments=True,
    settings_files=['settings.toml'],)

def setup_logger() -> None:
    if settings.is_debug:   # Here we check for IS_DEBUG variable in environment and in configuration file 
        level = 'DEBUG'
        diagnose = True
    else:
        level = 'INFO'
        diagnose = False
    logger.remove()  # Here we remove redundant loguru logger
    logger.add(  # And here we setup a new logger with desired level
        sys.stdout,
        level=level,
        diagnose=diagnose,
    )
```
Then, before my main function, I'm calling this `setup_logger()`.

Hope this solution helps.

**Comment by deknowny** [comment]
Thank you for so extensive answer! It helps! But anyway, there is no way set layered environments for environment variables, right?

**Comment by VaultVulp** [comment]
You are welcome!

As far as I know, layered configs are dynaconf-specific concepts, so there is no simple way to inject them into loguru's internals.

Can you express your problem a little bit more, please?
You can attach some configuration examples and describe the concrete result, you are trying to achieve.

**Comment by rochacbruno** [comment]
Environment variables has only a `DYNACONF_` prefix by default (it can be customized) so you can do something like

```bash
export MYAPP_DEVELOPMENT_DEBUG=true
export MYAPP_PRODUCTION_DEBUG=false
```

and

```py
from dynaconf import Dynaconf

settings = Dynaconf(
    envvar_prefix="MYAPP_DEVELOPMENT"
)
```

But I personally think there is no point on doing that, the idea of env vars is that they are specific to the environment, no need to have multiple layers.

Anyway another possibility is to store your logging in a dictionary.

```py
from dynaconf import Dynaconf

settings = Dynaconf(
    envvar_prefix="MYAPP"
)
```
then

```bash
export MYAPP_LOGGING__DEVELOPMENT__LEVEL=debug
export MYAPP_LOGGING__PRODUCTION__LEVEL=critical
```

Note the `__` to access nesting data.

If it doesn't help please reopen the issue with more context.
