### ISSUE TITLE
Is it possible to overwrite a configuration variable on the fly?

### ISSUE THREAD

**Issue by fillipe-gsm** [rochacbruno/dynaconf#599]
Suppose I have a Python project set up like this

```bash
.
├── main_script.py
├── project
│   ├── __init__.py
│   ├── module1.py
│   ├── module2.py
│   └── module3.py
└── settings.toml
```

Inside `settings.toml` I have a configuration variable set to a specific value, such as `config_variable = 1`, and a lot of modules inside `project/` call this variable with

```python
from config import settings

# Do something with `settings.config_variable`
```

Finally, `main_script.py` calls functions of the modules to perform a specific task.

What I need to do now is run `main_script.py` for multiple different values of `config_variable`. However, I have to manually update its value inside `settings.toml` so that the changes take effect and reexecute the script again and again.

Is there a way to programatically overwrite `config_variable` inside `main_script.py` so that I can run all different cases at once?

I tried overwriting the `settings.toml` file inside the script and reloading the file as explained [here](https://www.dynaconf.com/advanced/), but the changes do not persist over the modules.

Is it something possible to be done?

**Comment by rochacbruno** [comment]
I think you are looking for a centralized server to host your settings variables.

vault server, etcd or redis are good options.

Dynaconf supports vault and redis.
