### ISSUE TITLE
[RFC] Implement loader for AWS Infinidash config map

### ISSUE THREAD

**Issue by rochacbruno** [rochacbruno/dynaconf#607]
Our users are requesting support for Infinidash config map, this is going to be the highest priority feature for our 4.0 release.

Ex:

```py
from dynaconf import Dynaconf
from aws_infinidash import Dash

settings = Dynaconf()
settings.add_loader(Dash(aws_key=...., **options))

assert settings.my_dash_data == "my dash data"
```

This should allow the use of existing `Dash` instances.

**Comment by fjsj** [comment]
Should it also support the boto3 Infinidash client? I think it's the de facto standard client for Python.
