### ISSUE TITLE
RFC: Implement etcd loader plugin

### ISSUE THREAD

**Issue by rochacbruno** [rochacbruno/dynaconf#61]
Just like vault and redis
for

https://github.com/coreos/etcd

**Comment by rochacbruno** [comment]
https://github.com/Revolution1/etcd3-py

**Comment by yuanfeiz** [comment]
Any updates on this issue?

**Comment by rochacbruno** [comment]
Closing  by now,  I still want a loader for this service but I will personally not implement, waiting  for someone on community  to come  up with a new implementation.
