### ISSUE TITLE
[bug] envvar_prefix is not respected if using a loader other than env

### ISSUE THREAD

**Issue by zzZIMAWAKE** [rochacbruno/dynaconf#621]
**Describe the bug**
Apologies if this is not considered a bug but I found this behaviour slightly unexpected but perhaps I am misusing things.

If you load your settings from a file (as an example I'll make use of the ini loader) and you have `ENV_PREFIX` set, the settings that are loaded via the ini loader will not strip the prefix in the same way they would were they loaded via the environment.

I would expect all the loaders to behave in the same way stripping the prefix.

**To Reproduce**

1. Create a file: `touch dynaconf_settings.ini`
2. Add the following contents:
```
TESTING_my_env_var=123
what_what=123
wow_wow=123
TESTING_huh=123
```
3. `pip install "dynaconf[ini]"`
4. Set an env var pointing to the settings file - `export SETTINGS_FILE_FOR_DYNACONF=dynaconf_settings.ini`
5. Open up a shell `python3`
6. Run the following:
```
from dynaconf import Dynaconf
settings = Dynaconf(envvar_prefix="TESTING")

settings.my_env_var
<Error>
settings.TESTING_my_env_var=123
<returns '123'>
```

For clarity running the following:
`export TESTING_my_env_var=124`
`python3`
```
from dynaconf import Dynaconf
settings = Dynaconf(envvar_prefix="TESTING")

settings.my_env_var
<returns '124'>
```

as I would expect

**Expected behavior**
`settings.my_env_var` would store the value 123, as it would if this was loaded from an env var

**Environment (please complete the following information):**
 - OS: OSX
 - Dynaconf Version: 3.1.4
 - Frameworks in use: None

**Additional context**

Sorry if this is considered expected behaviour, its thrown a spanner in the works for what I had planned and curious whether this was intended. I'm planning to use dynaconf within a package that will allow users to set up configuration in various ways (env vars / ini files / toml files) and anticipated that they could call the variables the same in any of these cases e.g. `TESTING_my_env_var` in env / ini file / toml files and I'd still be able to reference it within the package as `settings.my_env_var`

If this is indeed a bug and you would like this behaviour to work as described above I'm happy to try and find some time to submit a pull request.

Thanks!

**Comment by rochacbruno** [comment]
@zzZIMAWAKE the env_prefix is meant to be used only for environment variable loading, we don't have a similar feature for other sources, is that useful? what is the use case? do you want to propose this as a new feature?

If you want multiple environments in a setting file you can use

```py
settings = Dynaconf(environments=True)
print(settings.KEY)
```

then

```toml
[my_environment1]
key = value

[my_environment2]
key = other value
```

```bash
ENV_FOR_DYANCONF=MY_ENVIRONMENT1 python app.py
```

**Comment by zzZIMAWAKE** [comment]
So the use case here is that I've created a package for health checks within an application and I want to give the user freedom as to how they set up their config. As this is health checks for resources they are already using within their application it is likely they already have config set up.

I think its best explained with an example, lets say you have RabbitMQ set up for your application and you want this health checks package to check its health. The package requires that it knows the broker url in order to health check that resource.

Within my application I may have that stored in an ini file as `RABBITMQ_BROKER_URL` along with every other setting for my application.

Another person using the package may have it set up as an env var named `RABBIT_URL`

In order to allow freedom of setup my plan was to suggest users of the package set up settings in the best way possible for them, using dynaconf's ini loader if they are currently using an ini, allow for automatic detection of env vars if they are currently using env vars, or use another of dynaconf's loaders such as toml etc.

I wanted a prefix to be used no matter the method as if they make use of `SETTINGS_FILE_FOR_DYNACONF` they're likely pulling in the config for their entire application whilst I'd like only to grab the values with the relevant prefix, in this case `HEALTH_CHECKS` an example is below:

`HEALTH_CHECKS_RABBITMQ_URL=%(RABBITMQ_BROKER_URL)s` added to the ini file for the first case
`export "HEALTH_CHECKS_RABBITMQ_URL=$RABBIT_URL"` for the second case

and refer to these within the package simply as `settings.RABBITMQ_URL` regardless of the loader used.

Does this make sense? Perhaps I'm missing a better solution for this type of problem.

I've really enjoyed working with dynaconf so far by the way 👍

**Comment by zzZIMAWAKE** [comment]
Provided it is okay with you @rochacbruno I can open a pull request for this feature.

My intention is to add an optional `settings_file_prefix` to `loader.load` which will default to None

Let me know if you're happy with that and I can get an PR up today for you to review.

**Comment by rochacbruno** [comment]
Yes, please add a test for that use case
