### ISSUE TITLE
Use @format with @casting like @int

### ISSUE THREAD

**Issue by EdwardCuiPeacock** [rochacbruno/dynaconf#642]
How can I use @format with @int together? For example in my settings.toml,

```
GPU_COUNTS = 4
num_gpus = "@int @format {this.GPU_COUNTS}"
```

Then `num_gpus` will still be parsed as strings rather than an integer.

**Comment by rochacbruno** [comment]
Hi @EdwardCuiPeacock we have been discussing this on #504 and looks like we need to bump this priority to solve the issue.

I think the plan is to change the Jinja/Format templating to wrap in `parse_conf` so the correct data type can be inferred.

**Comment by EdwardCuiPeacock** [comment]
@rochacbruno Sounds good. I read through that thread and this seems to be a more versatile solution.

**Comment by cutecutecat** [comment]
I met the similar situation. 
format + autocast is useful when inheriting config from parent structure.

**Comment by cutecutecat** [comment]
I have an idea of solving this.

It is clear that @format and @jinja convertor should support something like
`DB_PATH = "@format {env[HOME]}/{this.current_env}/{env[PROGRAM_NAME]}/{this.DB_NAME}"`

that a sentence constructed by **different data types**, thus cannot inferred to a single type, but **only str**.

If we create a new convertor **@value**, work like **@format**, but **only accept one value**

something like

`"@value": lambda value: Lazy(value, formatter=Formatters.value_formatter)`
and
```
class Formatters:
    """Dynaconf builtin formatters"""

    value_formatter = BaseFormatter(lambda value, setting: box_setting[value], "value")
```
to use it as
`num_gpus = "@value this.GPU_COUNTS"`
If you think this fix is appropriate, I would be happy to work on this!

**Comment by EdwardCuiPeacock** [comment]
> I have an idea of solving this.
> 
> It is clear that @Format and @Jinja convertor should support something like `DB_PATH = "@format {env[HOME]}/{this.current_env}/{env[PROGRAM_NAME]}/{this.DB_NAME}"`
> 
> that a sentence can be constructed by **different data types**, thus cannot inferred to a single type, but **only str**.
> 
> If we create a new convertor **@value**, work like **@Format**, but **only accept one value**
> 
> something like
> 
> `"@value": lambda value: Lazy(value, formatter=Formatters.value_formatter)` and
> 
> ```
> class Formatters:
>     """Dynaconf builtin formatters"""
> 
>     value_formatter = BaseFormatter(lambda value, setting: setting[value], "value")
> ```
> 
> to use it as `num_gpus = "@value this.GPU_COUNTS"` If you think this fix is appropriate, I would be happy to work on this!

Looking forward to this as a pull request.
