### ISSUE TITLE
Release 3.1.5 does not contain all commits since last release

### ISSUE THREAD

**Issue by zzZIMAWAKE** [rochacbruno/dynaconf#652]
Hey @rochacbruno, I updated to the latest version of dynaconf this morning but the strategies implementation is not included. Took a look at the latest [release commit](https://github.com/rochacbruno/dynaconf/commit/083f3c2497be8998524e16cae2cb2e24afc1332f) and it says it doesn't belong to a branch in this project and was likely created from a fork? Looking at the [parent](https://github.com/rochacbruno/dynaconf/commit/b0774d7d50e72fb4fa9d6ab60c0171db3612b400) of that commit and it is after the prefix strategy implementation but that [commit](https://github.com/rochacbruno/dynaconf/commit/0e47bf2a22d6f0c565085c3e8ea63bbb625ec150) doesn't seem to be included.

Any idea what has happened here?

**Comment by rochacbruno** [comment]
Hi,

3.1.5 was a z-stream release (a patch release for version 3.1.z)

It included just bug fixes, no new feature was added. https://github.com/rochacbruno/dynaconf/releases/tag/3.1.5

As master has some new features

- Filter strategies (ready)
- Selective validation (ready)
- Conditional variable attribution #632 (in progress)
- More mergin strategies (probably with schema) #299 (todo)

More bug fixes:

- Parse of Jinja and format fields  #642
- Django gettext lazy #648 


This will be a new `minor` (y) release and is included in 3.2.0 milestone https://github.com/rochacbruno/dynaconf/issues?q=is%3Aissue+sort%3Aupdated-desc+milestone%3A3.2.0+

I wish to release 3.2.0 soon, but I need to address the features on the roadmap.

If it takes too long, I can release a 3.2.0 with what we already have testes and then a 3.3 comes later.

**Comment by zzZIMAWAKE** [comment]
@rochacbruno Aha thanks for clarifying! Will close this

**Comment by rochacbruno** [comment]
@zzZIMAWAKE if you need we can release 3.2.0 soon, otherwise will wait for more implementation before releasing it.
