### ISSUE TITLE
[RFC] Add a dynaconf show command to view a single setting

### ISSUE THREAD

**Issue by daviddavis** [rochacbruno/dynaconf#660]
**Is your feature request related to a problem? Please describe.**
It would be nice to have a `dynconf show` command to display information for a single setting.

**Describe the solution you'd like**
```
$ dynaconf show MEDIA_ROOT
Name: MEDIA_ROOT
Type: str
Value: /var/lib/dynaconf/media
Location: /etc/dynaconf/settings.toml
...
```

**Comment by rochacbruno** [comment]
similar or duplicate of? #650

**Comment by daviddavis** [comment]
Yea, thank you. I'll close this as a dupe.
