### ISSUE TITLE
Change the README discussions to Github  New Feature

### ISSUE THREAD

**Issue by endersonmenezes** [rochacbruno/dynaconf#673]
In Readme there is a link that takes you to the telegram, which seems to me to be a not very used channel, could you fix the contributions guide and the readme to bring these discussions to our Github feature? I can do this myself, I brought the issue to understand if there is a convergence of thoughts.

**Comment by rochacbruno** [comment]
Good catch! I missed those updates, can you send a PR?

**Comment by mvadu** [comment]
shouldn't this be closed with #682  merged? @endersonmenezes ?
