### ISSUE TITLE
Install installs "tests" and "example" packages, in addition to "dynaconf"

### ISSUE THREAD

**Issue by simonpercivall** [rochacbruno/dynaconf#69]
`setup.py` specifies `packages=find_packages()`, which will include `tests` and `example`.

Perhaps `packages=find_packages(include=['dynaconf'])` would be better?

**Comment by rochacbruno** [comment]
Great! I think just `packages=['dynaconf']` would work!

**Comment by allan-silva** [comment]
Possible fix in #70

**Comment by rochacbruno** [comment]
Will be at the next release later this week
