### ISSUE TITLE
Don't configure the root logger

### ISSUE THREAD

**Issue by danilobellini** [rochacbruno/dynaconf#71]
As of today, importing dynaconf configures the handlers in the `logging` root logger, which [renders the `basicConfig` useless](https://docs.python.org/3/library/logging.html#logging.basicConfig):

> This function does nothing if the root logger already has handlers configured for it.

Example:

```
>>> import logging
>>> logging.basicConfig(format="[%(asctime)s|%(levelname)s] %(message)s",
...                     datefmt="%Y-%m-%dT%H:%M:%S")
>>> logging.error("Something")
[2018-06-23T18:21:03|ERROR] Something
```

The collateral effect of importing `dynaconf`:

```
>>> import logging
>>> import dynaconf
>>> logging.basicConfig(format="[%(asctime)s|%(levelname)s] %(message)s",
...                     datefmt="%Y-%m-%dT%H:%M:%S")
>>> logging.error("Something")
2018-06-23 18:21:59,723 - root - ERROR - Something
```

**Comment by chobeat** [comment]
I believe this is the problematic line, right?

https://github.com/rochacbruno/dynaconf/blob/38b26a8d5df5b78b14d7c696e5bd4a68b0222775/dynaconf/utils/__init__.py#L59

**Comment by chobeat** [comment]
I believe this is the problematic line:

https://github.com/rochacbruno/dynaconf/blob/38b26a8d5df5b78b14d7c696e5bd4a68b0222775/dynaconf/utils/__init__.py#L59

raw_logger() is called here: https://github.com/rochacbruno/dynaconf/blob/7d6758e27123b48ef45a475d9c1fdb94fb98bf0c/dynaconf/loaders/base.py#L6 

and it triggers during the import, right?

**Comment by rochacbruno** [comment]
I think we can then remove the call to `basicConfig`, @chobeat @danilobellini do you want to send a PR?

**Comment by rochacbruno** [comment]
Fixed by @chobeat it will be included in next release at the end of this week! thanks

**Comment by Sytten** [comment]
Hey @rochacbruno do you think you could do a release soon? Thanks :)

**Comment by rochacbruno** [comment]
@Sytten done! https://pypi.org/project/dynaconf/
