### ISSUE TITLE
Dotted key in YAML settings file

### ISSUE THREAD

**Issue by benbouillet** [rochacbruno/dynaconf#718]
Hello,

I work on a project where YAML is mandatory for configuration. In the `settings.yaml` file, we have some keys that includes `.` (dot) , but Dynaconf interprets it as a variables separator.

`- python=3.9.7`
`- dynaconf=3.1.7`

```yaml
# settings.yaml
default:
 www.google.com: true
```

```python
from dynaconf import Dynaconf
import yaml

settings = Dynaconf(
    settings_files=["config/settings.yaml"],
    environments=True,
)

print(yaml.dump(settings.as_dict(), sort_keys=False, default_flow_style=False))
```
returns
```python
WWW:
  GOOGLE:
    COM: true
```

I know that if we use the `.set` method, we can have a work-around :
```python
settings.set("www.google.com", True, dotted_lookup=False)
```
Returns:
```python
WWW.GOOGLE.COM: true
```

But I can't see a way to apply this `dotted_lookup` parameter to the YAML core loader.
I tried with simple & double quotes, also with escaping (`\.`), but without success.

Potential related issue #685 

Can you help please ?

**Comment by rochacbruno** [comment]
My proposal is that we add 2 things:

1. Fix #685 and a global config `DOTTED_LOOKUP=False` (will default to True)
2. Add a local version of this variable, so inside the yaml file one can do:
```yaml
---
dynaconf_dotted_lookup: false
default:
    www.google.com: data
```

There is already `dynaconf_merge` which works in similar way, we may have to allow more variables to be switched on that way.

---

I don't have time to work on anything related to dynaconf now and on the next 2-3 months, my only commit here is to cut a release at the end of this month, if someone can place a PR we can include in the next release.
