### ISSUE TITLE
[RFC] Add option to skip reloading on validators.validate 

### ISSUE THREAD

**Issue by rochacbruno** [rochacbruno/dynaconf#731]
On lines
https://github.com/rochacbruno/dynaconf/blob/master/dynaconf/validator.py#L202-L205

`validators.validate` is calling `from_env` and it makes the variables to be reloaded from source files.

This is not good for testing.

Solution:

1. Check if validation is happening on the same current env, then don't reload
2. accept argument `reload=False` that will cause those lines to pass `settings` direct to the `validate_items`

**Comment by cpt-nem0** [comment]
hey, can I work on this issue?
