### ISSUE TITLE
[RFC] Add option to validate only current env in validators.validate

### ISSUE THREAD

**Issue by UgoBena** [rochacbruno/dynaconf#734]
**Problem**
I currently have a problem in a project when trying to validate a configuration. I have some variables in production that I do not have in development environment, and that are contained in a .secrets file not present in my project. I would like to validate the presence of the production variables when I run the project in production environment. However when running the validators, they go through all environments, and thus fail when trying to validate my production environment in development because some variables are missing as the .secrets.yml file is not present.

**Proposed Solution**
I just wanted to know if you had considered this issue. I did a quick fix on my side by adding a `check_only_current_env: bool = False` var to all `validate` functions in [validators.py](https://github.com/rochacbruno/dynaconf/blob/master/dynaconf/validator.py) and simply add a check in `Validator.validate` before the [validate_items lines](https://github.com/rochacbruno/dynaconf/blob/master/dynaconf/validator.py#L193-L205):
```
if check_only_current_env:
    if settings.current_env in self.envs:
         this._validate_items(...)
    return
```

I am open to any other solutions and can also make a pull request with this small change.

Thank you very much for the project it's really nice !

**Comment by rochacbruno** [comment]
Similar feature has been implemented on https://github.com/rochacbruno/dynaconf/pull/549

this is doable at the validators level, you can pass `env` to the `Validator` class init.

You could for example make some validators valid only for `production` by passing it.

We can think on a more flexible way.

**Comment by UgoBena** [comment]
Yes that's exactly what I am doing however these validators will still be run on all environments even if I am in a different environment (`development` for instance) when I run `settings.validators.validate()`. Meaning they will fail as I don't have all the required variables in the production settings.

What I suggested was to add the option here to do `settings.validators.validate(check_only_current_env=True)`, kind of like the option to check only or exclude some settings with the `only` and `exclude` parameters
