### ISSUE TITLE
Cant find settings when running the program from another folder than root folder 

### ISSUE THREAD

**Issue by jgiudici** [rochacbruno/dynaconf#74]
Hi, I have this folder structure:
```

test_dynaconf
└── subfolder
    ├── main.py
    └── settings.toml
```

with main.py:
```
#main.py
from dynaconf import settings

print(settings["KEY1"])
```

and settings.toml: 

```
#settings.toml
[default]
KEY1="hi"
```

If I run from subfolder, everything works:
```
➜  subfolder python3 main.py 
hi
```

But if I run from test_dynaconf or another path, it breaks:
```
test_dynaconf python3 subfolder/main.py
Traceback (most recent call last):
  File "subfolder/main.py", line 3, in <module>
    print(settings["KEY1"])
  File "/usr/local/lib/python3.5/dist-packages/dynaconf/utils/functional.py", line 208, in inner
    return func(self._wrapped, *args)
  File "/usr/local/lib/python3.5/dist-packages/dynaconf/base.py", line 193, in __getitem__
    raise KeyError('{0} does not exists'.format(item))
KeyError: 'KEY1 does not exists'
```

**Comment by rochacbruno** [comment]
If you think it is valid to look for subfolders, please give me some time to try the implementation, I want do get some feedback about it before implementing.

**Comment by jgiudici** [comment]
The issue arises when I've tried to deamonize a script from supervisord, I've already resolved it with a config option of supervisord, but I think it has sense in the meaning that a script shouldn't be dependent of the pwd that was invoked if the script doesn't explicitly use a relative path to config.

**Comment by rochacbruno** [comment]
@jgiudici I'll make some tests, try to figure out scenarios where this can lead to errors and expect for more comments then maybe we can change it. I have also to check if it is easy to get dynamically the path for the called script.

**Comment by brucegibbins** [comment]
Hi. I am new to your package and I have recently introduced it to a colleague. The first question he had was if he can store the settings.yml in a sub-folder. We typically have a similar structure to the following where configuration settings are kept in a yaml file in a folder off the root of the package.

`\project
  \package
     \conf
      app.py
`
I too usually have this structure but simply moved my settings.yml to the same level as the app and thus benefited from the default behavior. We are a windows shop and could of course use the EXPORT environment variable equivalent at runtime but in my opinion it would be certainly beneficial to us if we could keep the configuration settings in a subfolder as an option.

**Comment by brucegibbins** [comment]
Thank you for your reply. As I am old coder but new to the python environ
please forgive my naive questions. Despite being aware of their purpose I
am unfamiliar with the workings of Flask or Django so cannot offer any
suggestions. However, would it not be possible to leave everything as you
currently have it but allow the calling module to set
PROJECT_ROOT_FOR_DYNACONF to use a relative path based on the module that
first instantiated settings? I may be missing a number of pythonic things
here and over simplifying it. But for us we would just like to be able to
override the default reading of settings.yml to use conf/settings.yml
instead. Our environment is a pure CLI so Flask and Django are not in our
focus at this stage. cheers
