### ISSUE TITLE
3.18 - It looks like this has broken integration with environment variables.

### ISSUE THREAD

**Issue by rochacbruno** [rochacbruno/dynaconf#741]
@rochacbruno @jyejare It looks like this has broken integration with environment variables.

If I have dynaconf 3.1.8 installed, and the combination of:

1. settings.yaml field key (nested one level from top map) is present, value is empty
2. validator with default=None for given field key
3. envvar set for nested field key (DYNACONF_something__field_key)
4. settings object configuration that looks like: https://github.com/SatelliteQE/robottelo/blob/master/robottelo/config/__init__.py#L18 

My envvar value is no longer set in the resulting box instance, it takes the validator default of `None`.

I confirmed its this line in particular by modifying the file in site-packages with 3.1.8 installed.

_Originally posted by @mshriver in https://github.com/rochacbruno/dynaconf/pull/729#discussion_r853220515_

**Comment by rochacbruno** [comment]
@mshriver tracking on this issue, so we can try to fix for both use cases and release 3.1.9 ASAP

**Comment by jyejare** [comment]
@mshriver @rochacbruno  I tried to reproduce this locally, but its not reproducible. I am getting the value from env as expected when the setting in conf is empty and the validator is set to default=None.

```
# grep SCOPE conf/shared_function.yaml
  SCOPE:

# grep scope robottelo/config/validators.py 
        Validator('shared_function.scope', default=None),

#  echo $ROBOTTELO_SHARED_FUNCTION__SCOPE 
local

# ipython
Python 3.9.12 (main, Mar 26 2022, 15:51:15) 

In [1]: from robottelo.config import settings
In [2]: settings.shared_function.scope
Out[2]: 'local'

```

@mshriver Can you share what setting in perticular is in the question ?

**Comment by rochacbruno** [comment]
@mshriver it woudl be useful to drop a reproducible example on https://github.com/rochacbruno/dynaconf/tree/master/example/issues 

Then we can run that example as part of the `functional` tests and ensure this keeps working on future versions.

**Comment by mshriver** [comment]
Trying to create an independent recreation of this, but its easy to see in our CI pipelines.  Below is a snippet from a Jenkins job, where within the container a value is set in the env, and is read with dynaconf 3.1.7 installed. When I install dynaconf 3.1.8, the envvar setting is no longer read.

```
09:52:48  + pip install dynaconf==3.1.7
09:52:48  Requirement already satisfied: dynaconf==3.1.7 in /opt/app-root/lib/python3.8/site-packages (3.1.7)
09:52:49  + python -c 'from robottelo.config import settings; print(settings.server.ssh_password)'
09:52:51  2022-04-25 13:52:51 - robottelo - WARNING - Dynaconf validation failed, continuing for the sake of unit tests
09:52:51      capsule.instance_name is required in env main
09:52:51  2022-04-25 13:52:51 - robottelo - WARNING - Dynaconf validation failed, continuing for the sake of unit tests
09:52:51      capsule.instance_name is required in env main
09:52:51  <redacted envvar string value>
09:52:51  + pip install dynaconf==3.1.8
09:52:52  Collecting dynaconf==3.1.8
09:52:52    Downloading dynaconf-3.1.8-py2.py3-none-any.whl (201 kB)
09:52:53  Installing collected packages: dynaconf
09:52:53    Attempting uninstall: dynaconf
09:52:53      Found existing installation: dynaconf 3.1.7
09:52:53      Uninstalling dynaconf-3.1.7:
09:52:53        Successfully uninstalled dynaconf-3.1.7
09:52:53  Successfully installed dynaconf-3.1.8
09:52:53  + python -c 'from robottelo.config import settings; print(settings.server.ssh_password)'
09:52:55  2022-04-25 13:52:55 - robottelo - WARNING - Dynaconf validation failed, continuing for the sake of unit tests
09:52:55      capsule.instance_name is required in env main
09:52:55  2022-04-25 13:52:55 - robottelo - WARNING - Dynaconf validation failed, continuing for the sake of unit tests
09:52:55      capsule.instance_name is required in env main
09:52:55  None
```

**Comment by mshriver** [comment]
I believe the following shows an independent reproducer, I've tried to attach the `config.py`, `conf/nested.yaml`, and a file containing envvar exports as well.

### Reproduction behavior

```
❯ python -c 'from config import settings; print(settings.nested.test_field)'
setbyenv

❯ python -c 'from config import settings; print(settings.nested.group_field)'
setbyenvgroup

❯ pip install dynaconf==3.1.8
Collecting dynaconf==3.1.8
  Using cached dynaconf-3.1.8-py2.py3-none-any.whl (201 kB)
Installing collected packages: dynaconf
  Attempting uninstall: dynaconf
    Found existing installation: dynaconf 3.1.7
    Uninstalling dynaconf-3.1.7:
      Successfully uninstalled dynaconf-3.1.7
Successfully installed dynaconf-3.1.8

❯ python -c 'from config import settings; print(settings.nested.test_field)'
None

❯ python -c 'from config import settings; print(settings.nested.group_field)'
setbyenvgroup
```

### Files

[envvar.txt](https://github.com/rochacbruno/dynaconf/files/8556569/envvar.txt)

[config.py.txt](https://github.com/rochacbruno/dynaconf/files/8556571/config.py.txt)

[nested.yaml.txt](https://github.com/rochacbruno/dynaconf/files/8556576/nested.yaml.txt)

**Comment by jyejare** [comment]
@mshriver I tried using the files in reproducer you have given in the last comment with dynaconf 3.1.8 version, but again its not reproducible locally :

STDOUT:
```
(rtello) ➜  roboDyns $ pip list | grep dynaconf
dynaconf                              3.1.8
(rtello) ➜  roboDyns $ env | grep TESTING
TESTING_nested__test_field=setbyenv
TESTING_nested__group_field=setbyenvgroup
(rtello) ➜  roboDyns $ python -c 'from config import settings; print(settings.nested.test_field)'
setbyenv
(rtello) ➜  roboDyns $ python -c 'from config import settings; print(settings.nested.group_field)'
setbyenvgroup
```

Not sure where its going wrong in your env. BTW I am using MAC and not sure if MAC treats it in a different way!

**Comment by rochacbruno** [comment]
Thanks @jmwielandt I added your tests (including you as co author of the commit)

@jyejare I will have to revert your PR #729 

This is the reason:

**YAML** doesn't differentiate `null` from `~` or `blank` values.

```yaml
key:
key: ~
key: null
``` 

On the example above, `ruamel.yaml` (parser used by dynaconf) loads everykey as the python  `None`.


So, the only way to have the default value set in the validator loaded would be not defining the value on the yaml, if the key is present in the YAML, then that value is used instead of the default.

I would like to provide alternatives, however this would require writing (or customizing) the ruamel.yaml parser to for example load undefined keys as a special value, and I don't have time to put on writing this solution right now, the RFC can be opened so someone from community can write it.

# So what is the plan?

1. I am reverting #729 
2. I am adding to the docs a caveat warning stating that undefined values on YAML are read as `None` so the default value is not considered
3. I am adding a special mark `@empty` so it will make possible to have `key: "@empty"` and in that case dynaconf will load it as an instance of the `empty` sentinel.
4. I am adding `Validator(..., apply_default_on_none=True)` to Validator so you can set if you want a validator default to be applied on None values.

Those changes are coming in `3.1.9`

**Comment by mshriver** [comment]
@rochacbruno thanks for capturing the root cause of this behavior :heart: 

Will the validator default to `apply_default_on_none=True` kwarg, making it the default behavior for dynaconf?  I think I'd otherwise have to end up setting this kwarg on every validator because I don't inherently know when a yaml value might have been parsed as None.

**Comment by jmwielandt** [comment]
@rochacbruno  thanks!



> @rochacbruno thanks for capturing the root cause of this behavior ❤️
> 
> Will the validator default to `apply_default_on_none=True` kwarg, making it the default behavior for dynaconf? I think I'd otherwise have to end up setting this kwarg on every validator because I don't inherently know when a yaml value might have been parsed as None.

**Idea:** what if `apply_default_on_none` is also a `LazySettings` attribute. Is set on `False` by default on both, Validators and LazySettings, and Validators can override for a specific setting the LazySettings' value.

My only concern is what could happen with other formats like toml, .env or environment variables.
