### ISSUE TITLE
[RFC] Custom validators

### ISSUE THREAD

**Issue by jurelou** [rochacbruno/dynaconf#748]
I'd like to use a custom validation method.

for example (check wether or not a given configuration entry is a valid regular expression):
```
def is_valid_regex(config):
  try:
    re.compile(config)
    return True
  except Exception:
    return False

settings = Dynaconf(
    validators=[
        Validator('test',  validate=is_valid_regex)
    ]
)
```

**Comment by rochacbruno** [comment]
this is exactly how it works today but the parameter to pass the function is `condition=function `
