### ISSUE TITLE
[RFC] Put newest version of documentation on readthedocs (dynaconf.com seems to be expired)

### ISSUE THREAD

**Issue by nizwiz** [rochacbruno/dynaconf#762]
**Is your feature request related to a problem? Please describe.**
RTD only contains documentation for v2.2.3, and dynaconf.com seems to be expired, so the current version of the documentation can only be seen using Google cache for dynaconf.com, AFAIK.

**Describe the solution you'd like**
Update the documentation on RTD.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by rochacbruno** [comment]
https://www.dynaconf.com/ is up

**Comment by nizwiz** [comment]
Thank you very much!
