### ISSUE TITLE
Inconsistent behavior between `yml` and `toml` approaches

### ISSUE THREAD

**Issue by arthur0** [rochacbruno/dynaconf#77]
Hi! 
First of all, you rock. Great project.

Bug description:

Environment: Flask Application

When you use `yaml` files, the `settings.yml(yaml)` and `.secret.yml(yaml)` are no loaded in the settings
When you use `toml` both are loaded, e.g.:
```bash
|- other/stuff
|- .env                     
|- manage.py
|- settings.yml(yaml)(toml)  # -->  Both settings are loaded from toml
|- .secrets.yml(yaml)(toml)  #      No settings are loaded from yaml/yml
```
Raises: 
```
(...) dynaconf/base.py", line 100, in __getattr__
    return getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'ATTRIBUTE'
```

Question: is there any way to use settings.**toml** and .secrets.**yml**?

**Comment by rochacbruno** [comment]
Good catch, I'll take a look soon. I assume it is possible to use `settings.toml` + `.secrets.yaml` the combination is free and the only thing to p[ay attention is the loading order.

For example:

if you have 

`export SETTINGS_MODULE_FOR_DYNACONF="foo.toml,bar.yaml,zas.json,.secrets.yaml, .s4cr3t5.yml"`

The settings must be loaded in the exact order defined in the above env var.

I'll try this use case and write a test for it.

**Comment by rochacbruno** [comment]
@arthur0 I am trying to reproduce the problem and it is working fine locally, 

have you installed YAML support? `pip install dynaconf[yaml]` ? or manually installed pyyaml?

Dynaconf comes with builtin toml support, but for yaml you need to add the extra requirement.

Is that the case of missing requirement?

https://dynaconf.readthedocs.io/en/latest/guides/usage.html#supported-file-formats

**Comment by arthur0** [comment]
Hello, it was my fault. 

I saw my Pipfile now and I did not installed the yaml support.

Once installed, works fine.

Thank you.
