### ISSUE TITLE
Python 3 compatiblity

### ISSUE THREAD

**Issue by andor44** [rochacbruno/dynaconf#8]
I haven't had time to find all the Python 3 incompatibilities but there's one I just ran into [here](https://github.com/rochacbruno/dynaconf/blob/524fd963c9c0b9965d4323e83f2086357f84ec5e/dynaconf/base.py#L316). `basestring` is not a thing in Python 3 anymore.

**Comment by rochacbruno** [comment]
Thanks @andor44 I will work on implementing all the possibilities using **six** package alternatives.

**Comment by aholik** [comment]
A note on Redis backend:

Python 3 receives bytes from Redis, I had to use `'decode_responses': True` option in `REDIS_FOR_DYNACONF` otherwise the loader failed.

**Comment by rochacbruno** [comment]
Yeah another problem with namespaces https://repl.it/EHWD

can someone take a look?

**Comment by rochacbruno** [comment]
@aholik I should put a note on docs for that.

**Comment by rochacbruno** [comment]
Covered in 0.3.0 version thanks you all
