### ISSUE TITLE
Problem encoding utf-8 in windows

### ISSUE THREAD

**Issue by victorpb** [rochacbruno/dynaconf#81]
I have a settings written in linux, with utf-8, however when running on windows it is being read as cp1252 which shows invalid characters. :(

**Comment by victorpb** [comment]
I'm use toml. 

I solved by forcing the encode to 'utf-8' in https://github.com/rochacbruno/dynaconf/blob/master/dynaconf/loaders/base.py#L86

**Comment by rochacbruno** [comment]
@victorpb nice! would be good to have a default encoding set to `utf-8` and then enable to be overwritten via `ENCODING_FOR_DYNACONF=iso8859-1` envvar.

I'll fix this soon.

**Comment by rochacbruno** [comment]
@victorpb implemented you suggestion in #83 will merge soon and release the new version after the tests.
