### ISSUE TITLE
RFC: Allow dot traversing to access nested dictionaries

### ISSUE THREAD

**Issue by rochacbruno** [rochacbruno/dynaconf#84]
Lets take a `settings.yaml`

```yaml
DEFAULT:
    REDIS:
        HOST: localhost
        PORT: 1234
```

To access the `port` you need to use one of:

```python
settings.REDIS['PORT']        # may raise KeyError
settings['REDIS']['PORT']      # may raise KeyError
settings.REDIS.PORT           # possible because it is a Box(), but may raise AtributeError
settings.get('REDIS').PORT  # dict like get method
settings('REDIS')['PORT']      # the same as calling .get
settings.get('REDIS').get('PORT')  # may raise AttributeError
```

But what if you are not sure that the `REDIS` value is defined in `settings.yaml` and you don't wanna fail?

one way is relying on the `.get` default argument (dict like)

```python
settings.get('REDIS', {}).get('PORT', 1234)
```

## RFC: Allow traversing

```python
settings('REDIS.PORT')   # would access the settings['REDIS']['PORT'] or raise KeyError.

settings('REDIS.PORT', 1234)   # if value cannot be accessed returns 1234 by default
```

The `.` should be parsed on `LazySettings.get` method and then perform the traversing.

### Requirements
- [ ] Avoid regressions (keep backwards compatibility)
- [ ] Allow it to be disabled `opt-out`
- [ ] Ensure it does not include overhead by recursion and traversing
- [ ] Document it
- [ ] Write test cases
- [ ] Write examples/

**Comment by allan-silva** [comment]
@rochacbruno, considering the given `yaml`, what should happen when the `REDIS` entry does not exist?

**Comment by rochacbruno** [comment]
@allan-silva this feature has been implemented!

If the base `REDIS` does not exists then it raises keyerror.
