### ISSUE TITLE
Add ability to specify a default location for settings file

### ISSUE THREAD

**Issue by dkliban** [rochacbruno/dynaconf#87]
Users of Django apps have to specify a 'DYNACONF_SETTINGS' environment variable to specify where their settings file is located. Application writers would benefit from being able to set a SETTINGS config in their settings.py which would provide a default location for a settings file. If the file is not present, dynaconf should log this, and allow django to start up normally.

**Comment by rochacbruno** [comment]
Hi @dkliban I think this issue is related to #73  

In your case when using Django I guess (need to test it) you can put in your `settings.py`

```python
SETTINGS_MODULE_FOR_DYNACONF=/etc/foo.yml
```

Then this value would be the default unless it is overwritten by environment variable `{PREFIX}_SETTINGS`

**Comment by dkliban** [comment]
That worked for me! Thank you @rochacbruno
