### ISSUE TITLE
RFC: Allow dot notation for .set method

### ISSUE THREAD

**Issue by rochacbruno** [rochacbruno/dynaconf#96]
Dot traversal access has been implemented by @jperras in #93 

Now it is possible to read values like `settings['DICT.KEY.NESTED.OTHER']` 

But the set method does not have this functionality.

```py
settings.set('DICT.KEY.NESTED.OTHER', 1)
{
   'DICT.KEY.NESTED.OTHER':  1
}
```

But what we want is

```py
settings.set('DICT.KEY.NESTED.OTHER', 1)
{
   'DICT': {
     'KEY': {
        'NESTED': {
            'OTHER':  1
        }
     }
  }
}
```

Unless we explitly pass `dotted_lookup=False`

- [ ] Keep backwards compatibility
- [ ] Add unit tests
- [ ] Add a use case in `examples/`
- [ ] opt-out via explicit param `.set(x, y, dotted_lookup=False)`
- [ ] opt-out globally via `NESTED_SET_ENABLED_FOR_DYNACONF=False`
- [ ] work well with the new MERGE feature that was included #88

**Comment by anudeepsamaiya** [comment]
@rochacbruno  can I take this issue?

**Comment by rochacbruno** [comment]
@anudeepsamaiya sure you can. 

This issue can be implemented using https://github.com/cdgriffith/Box#default-box following the same logic used in `.get` method (using the '.' to detect the nested keys)
